In [1]:
# HypotheSAEs Quickstart
# This notebook demonstrates basic usage of HypotheSAEs on a sample of the Yelp review dataset
import os

%load_ext autoreload
%autoreload 2

import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'  # Set to '0' to use the first GPU, or 'cpu' to run on CPU
os.environ['OPENAI_KEY_SAE'] = 'EMPTY' # Replace with your OpenAI API key, or with another environment variable (e.g. os.environ['OPENAI_API_
import numpy as np
import pandas as pd

from hypothesaes.quickstart import train_sae, interpret_sae, generate_hypotheses, evaluate_hypotheses
from hypothesaes.embedding import get_openai_embeddings, get_local_embeddings

/home/sevan/anaconda3/envs/llm/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

**Load data**

The dataset we're using here is a subset of 20K Yelp reviews, with 2K reviews used for validation (during SAE training). 

The target variable is the `stars` column, which is a rating between 1 and 5. We treat this as a regression task.

There are also 2K reviews used for holdout evaluation, which we'll use at the end of the notebook.

In [8]:
CACHE_SIGNAL = "concurrent"

In [9]:
current_dir = os.getcwd()
if current_dir.endswith("notebooks"):
    prefix = "../"
else:
    prefix = "./"
val_ratio = 0.1  # Ratio of training data to use for validation
import sklearn
import sklearn.model_selection
few_shot_examples = 5
# base_dir = os.path.join(prefix, "demo-data")
# train_df = pd.read_json(os.path.join(base_dir, "yelp-demo-train-20K.json"), lines=True)
# val_df = pd.read_json(os.path.join(base_dir, "yelp-demo-val-2K.json"), lines=True)

# texts = train_df['text'].tolist()
# labels = train_df['stars'].values
# val_texts = val_df['text'].tolist() # These are only used for early stopping of SAE training, so we don't need labels.
from utils import df_to_prompts
import json
import re
base_dir = os.path.join(prefix, 'com_data')
train_X = pd.read_csv(os.path.join(base_dir, "X_train.csv"))
train_y = pd.read_csv(os.path.join(base_dir, "y_train.csv")).values.ravel()
test_X = pd.read_csv(os.path.join(base_dir, "X_test.csv"))
test_y = pd.read_csv(os.path.join(base_dir, "y_test.csv")).values.ravel()
label_type = set(train_y).union(set(test_y))
# number_dict = {label: i for i, label in enumerate(label_type)}
number_dict = {label: 1 if label == 'Home' else 0 for label in label_type}
label_train = [number_dict[label] for label in train_y]
label_test = [number_dict[label] for label in test_y]
# train_texts = df_to_prompts(few_shot_row, few_shot_label, train_X.iloc[few_shot_examples:, :], few_shot_examples=few_shot_examples)
pattern = re.compile(r"<think>.*?</think>", re.DOTALL)  # 匹配 <think> 到 </think>，包括换行
train_texts_idx_profile = []
test_texts_idx_profile = []
train_jsonl = os.path.join(base_dir, f"train_profile_{CACHE_SIGNAL}.jsonl")
test_josnl = os.path.join(base_dir, f"test_profile_{CACHE_SIGNAL}.jsonl")
if len(CACHE_SIGNAL) == 0 or 'toy' in CACHE_SIGNAL :
    train_jsonl = os.path.join(base_dir, "train_profile_toy.jsonl")
    test_josnl = os.path.join(base_dir, "test_profile_toy.jsonl")
with open(train_jsonl) as f:
    for line in f:
        obj = json.loads(line)
        profile = obj["profile"]
        profile = re.sub(pattern, "", profile)  # 删除 <think>...</think>
        obj["profile"] = profile.strip()
        train_texts_idx_profile.append((obj['profile'], obj['idx']))
    sorted_train_texts_idx_profile = sorted(train_texts_idx_profile, key=lambda x: x[1])
train_texts = [item[0] for item in sorted_train_texts_idx_profile]
with open(test_josnl)as f:
    for line in f:
        obj = json.loads(line)
        profile = obj["profile"]
        profile = re.sub(pattern, "", profile)  # 删除 <think>...</think>
        obj["profile"] = profile.strip()
        test_texts_idx_profile.append((obj['profile'], obj['idx']))
    sorted_test_texts_idx_profile = sorted(test_texts_idx_profile, key=lambda x: x[1])
test_texts = [item[0] for item in sorted_test_texts_idx_profile]
print(set(train_y), set(test_y))    
number_dict

{'Home with Services', 'Deceased / Hospice', 'Home', 'Facility-Based Care'} {'Home with Services', 'Deceased / Hospice', 'Home', 'Facility-Based Care'}

{'Deceased / Hospice': 0,
 'Home with Services': 0,
 'Home': 1,
 'Facility-Based Care': 0}

In [10]:
#count label distribution
train_label_distribution = pd.Series(train_y).value_counts()
test_label_distribution = pd.Series(test_y).value_counts()
train_label_distribution,  test_label_distribution

(Home                   3419
 Facility-Based Care    1391
 Home with Services     1339
 Deceased / Hospice      615
 Name: count, dtype: int64,
 Home                   180
 Facility-Based Care     74
 Home with Services      71
 Deceased / Hospice      32
 Name: count, dtype: int64)

In [11]:
texts, val_texts, labels, val_labels = sklearn.model_selection.train_test_split(
    train_texts, label_train, test_size=val_ratio, random_state=42, shuffle=True
)

**Compute text embeddings for your dataset**

We'll compute text embeddings for a training set, and optionally a validation set. The validation embeddings are used for SAE eval and early-stopping during training.

Embeddings will be stored in the `emb_cache` directory (or `os.environ["EMB_CACHE_DIR"]` if you set it) using the `cache_name` parameter, so you only need to compute embeddings once.

You can use OpenAI or a local model.

Local models will run much faster on GPU. The default local model is `nomic-ai/modernbert-embed-base`. You can use any sentence-transformers model, but please read the model's docs; you may need to edit `get_local_embeddings`.

In [12]:
EMBEDDER = "Qwen/Qwen3-Embedding-0.6B" # OpenAI
# EMBEDDER = "nomic-ai/modernbert-embed-base" # Huggingface model, will run locally
CACHE_NAME = f"yelp_quickstart_{EMBEDDER}"

# text2embedding = get_openai_embeddings(texts + val_texts, model=EMBEDDER, cache_name=CACHE_NAME)
text2embedding = get_local_embeddings(texts + val_texts, model=EMBEDDER, batch_size=32, cache_name=CACHE_NAME)
embeddings = np.stack([text2embedding[text] for text in texts])

train_embeddings = np.stack([text2embedding[text] for text in texts])
val_embeddings = np.stack([text2embedding[text] for text in val_texts])
text2embedding_test = get_local_embeddings(test_texts, model=EMBEDDER, batch_size=8, cache_name=CACHE_NAME)
test_embeddings = np.stack([text2embedding_test[text] for text in test_texts])

Loading embedding chunks: 100%|██████████| 8/8 [00:00<00:00, 56.60it/s]

Loaded 13614 embeddings in 0.1s

Loading embedding chunks: 100%|██████████| 8/8 [00:00<00:00, 62.41it/s]

Loaded 13614 embeddings in 0.1s

**Train SAE(s)** 

Using different values of $M$ and $k$ will produce features at different levels of granularity. You can train multiple SAEs if you'd like to produce features at varying granularity, but this is optional.

See the README for more details about selecting $M$ and $k$.

In [13]:
checkpoint_dir = os.path.join(prefix, f"checkpoints_{CACHE_SIGNAL}", CACHE_NAME)
# sae_256_8 = train_sae(embeddings=train_embeddings, M=256, K=8, checkpoint_dir=checkpoint_dir, val_embeddings=val_embeddings, n_epochs=1000, patience=100)
# sae_32_4 = train_sae(embeddings=train_embeddings, M=32, K=4, checkpoint_dir=checkpoint_dir, val_embeddings=val_embeddings, n_epochs=1000, patience=100)
# sae_512_8 = train_sae(embeddings=train_embeddings, M=512, K=8, checkpoint_dir=checkpoint_dir, val_embeddings=val_embeddings, n_epochs=1000, patience=100)
sae_128_64 = train_sae(embeddings=train_embeddings, M=128, K=8, checkpoint_dir=checkpoint_dir, val_embeddings=val_embeddings, n_epochs=1000, patience=100)
sae_128_16 = train_sae(embeddings=train_embeddings, M=128, K=16, checkpoint_dir=checkpoint_dir, val_embeddings=val_embeddings, n_epochs=1000, patience=100)
sae_256_16 = train_sae(embeddings=train_embeddings, M=256, K=16, checkpoint_dir=checkpoint_dir, val_embeddings=val_embeddings, n_epochs=1000, patience=100)
sae_128_32 = train_sae(embeddings=train_embeddings, M=128, K=32, checkpoint_dir=checkpoint_dir, val_embeddings=val_embeddings, n_epochs=1000, patience=100)
sae_256_32 = train_sae(embeddings=train_embeddings, M=256, K=32, checkpoint_dir=checkpoint_dir, val_embeddings=val_embeddings, n_epochs=1000, patience=100)
sae_512_32 = train_sae(embeddings=train_embeddings, M=512, K=32, checkpoint_dir=checkpoint_dir, val_embeddings=val_embeddings, n_epochs=1000, patience=100)
sae_128_64 = train_sae(embeddings=train_embeddings, M=128, K=64, checkpoint_dir=checkpoint_dir, val_embeddings=val_embeddings, n_epochs=1000, patience=100)
sae_256_64 = train_sae(embeddings=train_embeddings, M=256, K=64, checkpoint_dir=checkpoint_dir, val_embeddings=val_embeddings, n_epochs=1000, patience=100)
sae_list = [sae_128_32, sae_128_64, sae_256_64]

Loaded model from ./checkpoints_concurrent/yelp_quickstart_Qwen/Qwen3-Embedding-0.6B/SAE_M=128_K=8.pt onto device cuda
Loaded model from ./checkpoints_concurrent/yelp_quickstart_Qwen/Qwen3-Embedding-0.6B/SAE_M=128_K=16.pt onto device cuda
Loaded model from ./checkpoints_concurrent/yelp_quickstart_Qwen/Qwen3-Embedding-0.6B/SAE_M=256_K=16.pt onto device cuda
Loaded model from ./checkpoints_concurrent/yelp_quickstart_Qwen/Qwen3-Embedding-0.6B/SAE_M=128_K=32.pt onto device cuda
Loaded model from ./checkpoints_concurrent/yelp_quickstart_Qwen/Qwen3-Embedding-0.6B/SAE_M=256_K=32.pt onto device cuda
Loaded model from ./checkpoints_concurrent/yelp_quickstart_Qwen/Qwen3-Embedding-0.6B/SAE_M=512_K=32.pt onto device cuda
Loaded model from ./checkpoints_concurrent/yelp_quickstart_Qwen/Qwen3-Embedding-0.6B/SAE_M=128_K=64.pt onto device cuda
Loaded model from ./checkpoints_concurrent/yelp_quickstart_Qwen/Qwen3-Embedding-0.6B/SAE_M=256_K=64.pt onto device cuda

**Interpret neurons**  

Interpret a random subset of neurons in the SAE to sanity-check that the learned features, and their interpretations, seem reasonable. We generate and print labels for `n_random_neurons` neurons, and we also print out the top-activating texts for each neuron.

In [8]:
# This instruction will be included in the neuron interpretation prompt.
# The below instructions are specific to Yelp, but you can customize this for your task.
# If you don't pass in task-specific instructions, there is a generic instruction (see src/interpret_neurons.py);
# task-specific instructions are optional, but they help produce hypotheses at the desired level of specificity.

TASK_SPECIFIC_INSTRUCTIONS = "You are a medical assistant. All of the texts are descripting patients' basic information, medical conditions and treatments, such as diastolic_bp, systolic_bp and age. You need add hypothesis for each neuron, which should describe a specific aspect of the text. " 
# """All of the texts are reviews of restaurants on Yelp.
# Features should describe a specific aspect of the review. For example:
# - "mentions long wait times to receive service"
# - "praises how a dish was cooked, with phrases like 'perfect medium-rare'\""""
# Interpret random neurons
results = interpret_sae(
    texts=texts,
    embeddings=train_embeddings,
    sae=sae_list,
    n_random_neurons=30,
    print_examples_n=10,
    task_specific_instructions=TASK_SPECIFIC_INSTRUCTIONS,
    interpreter_model="Qwen/Qwen3-32B",
    annotator_model="Qwen/Qwen3-32B",  # Use the same model for both interpretation and annotation
    max_interpretation_tokens= 1024,
)

Computing activations (batchsize=16384):   0%|          | 0/1 [00:00<?, ?it/s]

Computing activations (batchsize=16384): 100%|██████████| 1/1 [00:00<00:00,  4.44it/s]
Computing activations (batchsize=16384): 100%|██████████| 1/1 [00:00<00:00, 133.01it/s]
Computing activations (batchsize=16384): 100%|██████████| 1/1 [00:00<00:00, 98.37it/s]

Activations shape: (6087, 512)

Generating 1 interpretation(s) per neuron: 100%|██████████| 30/30 [00:07<00:00,  3.82it/s]

Neuron 350 (from SAE M=256, K=64): <think>

</think>

- "The text includes a normal BMI or blood pressure reading, with specific values provided that fall within healthy clinical ranges, and mentions the absence of immediate cardiovascular or metabolic concerns.

Top activating examples:
1. The patient is a 44-year-old married female presenting with a normal BMI of 19.2, calculated from her height of 69 inches and weight of 130 pounds, indicating a healthy weight status. Her blood pressure of 100/70 mmHg falls within the normal range, suggesting no immediate cardiovascular concerns. Despite these favorable metrics, her recent emergency admission to the emergency room highlights an acute healthcare need, though the length of stay was brief (1 day), and this remains her only documented encounter to date. The lack of prior records may reflect either limited healthcare utilization or a newly emerging health issue requiring further contextual investigation. While her demographic profile—white race, English language preference, and unspecified insurance category—does not independently signal heightened risk, the emergency admission underscores the importance of evaluating the underlying cause of her acute presentation to identify any latent conditions. Given her current stability, targeted interventio[... rest of text is truncated]
2. The patient is a 60-year-old white female with a normal BMI of 22.1, indicating a healthy weight distribution for her height of 63 inches (5 feet 3 inches) and weight of 125 pounds. Her current blood pressure reading of 110/76 mmHg falls within the optimal range, suggesting良好的 cardiovascular status at the time of assessment. However, her recent urgent admission to the hospital, following transfer from a skilled nursing facility, highlights a significant healthcare utilization event marked by an 18-day inpatient stay—a duration indicative of complex care needs or a prolonged acute episode. While her demographic profile (divorced, English-speaking) does not immediately signal social determinants of health disparities, the combination of her age, gender, and institutional care setting warrants attention to risks such as postmenopausal osteoporosis, mobility-related injuries, or complications from prolonged immobility during hospitalization. The absence of chronic condition documentation in her two recorded encou[... rest of text is truncated]
3. The 42-year-old female patient presents with a normal BMI of 19.9, calculated from her height of 64.5 inches (5 feet 4.5 inches) and weight of 118 pounds, indicating a healthy weight distribution for her stature. Her blood pressure of 94/66 mmHg falls within the normal range, though the diastolic reading approaches the lower end of typical values, warranting cautious monitoring for potential hypotensive symptoms such as dizziness or fatigue, particularly given her recent urgent admission. This visit, triggered by a physician referral and resulting in a 4-day hospital stay, marks her first documented encounter in the healthcare system (zero prior records), suggesting either new patient status or underutilization of services. While her demographic profile—married, English-speaking, and white—does not immediately signal heightened risk for socially driven health disparities, the absence of prior records raises questions about continuity of preventive care, such as routine cancer screenings or cardiovascular asse[... rest of text is truncated]
4. The patient is a 51-year-old white female with a normal BMI of 21.3, reflecting a healthy weight for her height of 67 inches (5 feet 7 inches) and weight of 136 pounds. Her blood pressure, measured at 120/75 mmHg, falls within the optimal range, indicating no immediate cardiovascular strain. Admitted urgently from a transfer hospital, her 5-day inpatient stay suggests a need for acute care, though her lack of prior records in this system implies she may be a new user of this healthcare facility or previously underserved. As a divorced individual without specified social support details, potential gaps in care adherence or post-discharge assistance warrant consideration. While her current biometrics demonstrate no overt metabolic or cardiovascular risk, her age and gender align with increased vulnerability to conditions such as osteoporosis or menopause-related health shifts, though no related data are present here. Given her "other" insurance classification, which may signal limited coverage or reliance on al[... rest of text is truncated]
5. The patient is a 40-year-old married white female with a body mass index (BMI) of 19.2, placing her within the normal weight range for her height of 62 inches (5 feet 2 inches) and weight of 105 pounds. Her recent surgical same-day admission, characterized by a brief hospital stay of 2 days, suggests a procedure with minimal postoperative complications, though further clinical context would clarify the specific intervention. Blood pressure measurements of 107 mmHg systolic and 72 mmHg diastolic indicate normotension, aligning with her currently stable cardiovascular status. Notably, this admission was facilitated through physician referral, and her medical history contains no prior records, implying either a previously low-utilization pattern or a lack of established longitudinal care. While her demographic profile—comprising age, BMI, and blood pressure—does not immediately signal metabolic or cardiovascular risk factors, her lower weight percentile for height (105 lbs at 62 inches) warrants monitoring for p[... rest of text is truncated]
6. The patient is a 36-year-old white female with a normal blood pressure reading of 110/70 mmHg, indicating no immediate hypertensive concerns; however, the absence of height and body mass index (BMI) data limits a comprehensive assessment of weight-related health risks. Admitted via physician referral for a surgical same-day procedure with a 3-day length of stay, her healthcare utilization suggests a planned, coordinated intervention rather than an acute crisis. As a single individual with “other” insurance, potential socioeconomic or logistical barriers to postoperative care or preventive services may warrant consideration, though her young age and current vital signs point to an otherwise stable baseline. The lack of recorded BMI and height, despite a documented weight of 156 lbs, represents a critical gap in evaluating metabolic or cardiovascular risk factors. Additionally, the presence of three prior medical records hints at intermittent engagement with healthcare services, which could reflect episodic car[... rest of text is truncated]
7. The 39-year-old male patient presents with a normal body mass index (BMI) of 20.5, reflecting a healthy weight of 153 pounds for his height of 70.5 inches, which aligns with standard clinical benchmarks for weight management. His blood pressure measurements of 108/74 mmHg fall within the optimal range, suggesting良好的 cardiovascular health and minimal immediate risk for hypertension-related complications. However, his recent admission to the emergency room under an "emergency" designation, with a length of stay of five days, indicates an acute or urgent health event that warrants further investigation into the underlying cause, though specific diagnoses remain unspecified in the provided data. Over the past documented period, eight medical records highlight frequent healthcare engagement, potentially signaling either proactive management of a transient condition or a barrier to accessing non-urgent care, though his normal BMI and blood pressure do not currently suggest chronic disease complexity. As a single in[... rest of text is truncated]
8. The patient is a 26-year-old Asian female presenting with a normal body mass index (BMI) of 19.1, placing her within the "Normal" weight category, though the absence of recorded height limits the ability to validate this calculation against standard formulas. Her blood pressure readings of 110/70 mmHg fall within the optimal range, indicating no immediate cardiovascular concerns. This visit marks her first documented healthcare encounter, as indicated by the "0" number of prior records, and she was urgently admitted via physician referral, suggesting a targeted response to an acute issue rather than a routine checkup. Her two-day length of stay aligns with brief, focused treatment episodes, though the lack of longitudinal data obscures patterns of chronic condition management or preventive care utilization. While her demographic profile—married, English-speaking, and insured under an unspecified category—does not inherently signal elevated risk, the absence of height and limited historical health data create [... rest of text is truncated]
9. The 40-year-old married white female presents with a normal BMI of 24.3, calculated using her recorded weight of 131 lbs, though her height remains unlisted in the dataset, limiting further anthropometric analysis. Her blood pressure measurements of 99 mmHg systolic and 64 mmHg diastolic fall within the normotensive range, suggesting no immediate cardiovascular compromise. However, her admission via the emergency room with a 10-day length of stay indicates a significant acute health event, though the specific diagnosis remains unspecified in the provided records. Healthcare utilization patterns reveal five associated medical records for this encounter, potentially reflecting multiple documentation points during her hospitalization or prior interactions, though longitudinal data gaps persist. As a married adult in her fourth decade of life, she may face modifiable risks such as stress-related hypertension or metabolic shifts, though current vitals show no such evidence. The "other" insurance category warrants [... rest of text is truncated]
10. The 51-year-old male patient presents with a normal blood pressure reading of 121/75 mmHg, indicating no immediate hypertensive concerns, though longitudinal monitoring would be prudent to assess trends. Admitted for a surgical same-day procedure via physician referral, his four-day length of stay suggests a potentially uncomplicated postoperative recovery, though the absence of prior medical records in the system raises questions about the continuity of care and preexisting health conditions. As a married, English-speaking individual with "other" insurance, socioeconomic or access-related barriers to care could not be ruled out, particularly given the lack of documented healthcare utilization history. While his weight of 175 lbs is recorded, the absence of height data precludes a definitive BMI calculation, limiting the ability to assess metabolic or cardiovascular risks associated with obesity or undernutrition. His white race and middle-aged demographic position him at moderate risk for age-related comorbi[... rest of text is truncated]
----------------------------------------------------------------------------------------------------

Neuron 5 (from SAE M=128, K=32): <think>

</think>

- "Mentions Black/Cape Verdean race

Top activating examples:
1. The patient is a 32-year-old Black/Cape Verdean male presenting for emergency care, with a recorded systolic/diastolic blood pressure of 116/68 mmHg, which falls within the normal range, suggesting no immediate hypertensive concern. However, the absence of height data precludes a definitive BMI calculation, though his weight of 191 lbs raises the need for further anthropometric assessment to evaluate metabolic health risks, particularly given disparities in obesity- and diabetes-related outcomes observed in Cape Verdean populations. Admitted through the emergency room under an emergency admission type, his 7-day hospitalization indicates a potentially complex or acute presentation, though the lack of prior medical records suggests either a new entrant to the healthcare system or a previously undiagnosed condition. His marital status may provide social support, yet his insurance classification as "other" could signal potential barriers to consistent care or preventive services. Key risks include undiagnosed me[... rest of text is truncated]
2. The 48-year-old Portuguese woman presents with a normal body mass index (BMI) of 22.8, calculated from her height of 66 inches (5 feet 6 inches) and weight of 141.09 pounds, indicating a healthy weight distribution for her stature. Her current blood pressure reading of 116/70 mmHg falls within the optimal range, suggesting no immediate cardiovascular strain. However, her recent emergency room admission under an observation admit category, with a 2-day hospital stay, highlights an acute health concern that required short-term monitoring, though the underlying cause remains unspecified in the provided data. Over her medical history, she has generated three clinical records, reflecting sporadic healthcare engagement, which may indicate either targeted care for specific issues or potential underutilization of preventive services.    As a married, English-speaking adult on Medicare, her sociodemographic profile suggests access to care, yet the absence of chronic condition documentation raises questions about the n[... rest of text is truncated]
3. This 43-year-old Black/Cape Verdean male presents with a normal BMI of 23.4, calculated from his height of 65 inches and weight of 156.1 lbs, indicating a healthy weight distribution for his stature. His blood pressure reading of 123/85 mmHg reveals a systolic value within the optimal range but a diastolic pressure at the upper threshold of normal, warranting cautious monitoring for early signs of hypertension, particularly given his age and gender, which are associated with increased cardiovascular risk in population health studies. Admitted for observation following a transfer from another hospital, his brief one-day length of stay and the presence of eight prior medical records suggest intermittent healthcare engagement, potentially reflecting episodic rather than proactive management of health concerns. As a single individual with Medicare insurance, social determinants such as limited social support networks and potential access barriers may influence his healthcare-seeking behavior. While his current me[... rest of text is truncated]
4. This 24-year-old Black/Cape Verdean woman presents as a young adult with a current BMI of 25.2, classifying her as overweight, though her blood pressure (110/68 mmHg) remains within the normal range, suggesting no immediate cardiovascular strain. Standing 66.5 inches tall and weighing 156 pounds, her health profile highlights a key area for intervention in weight management to mitigate long-term risks such as metabolic syndrome or type 2 diabetes, which are disproportionately prevalent in Black populations. Her urgent admission via physician referral, coupled with a 3-day hospital stay, indicates an acute health event necessitating prompt care, though her lack of prior medical records suggests limited documented engagement with healthcare services to date. As an English-speaking single individual with "other" insurance coverage, potential barriers to preventive care—such as financial constraints or fragmented access—may contribute to reactive rather than proactive healthcare utilization. Given her age and cur[... rest of text is truncated]
5. The 36-year-old Portuguese female patient presents with a BMI of 26.7, classifying her as overweight, though her blood pressure (122/72 mmHg) falls within the normal range, suggesting no immediate cardiovascular strain. Admitted urgently via physician referral for a four-day hospital stay, her utilization pattern indicates a reactive rather than proactive approach to healthcare, potentially signaling unmet needs in outpatient management or preventive care. Her demographic profile—married, publicly insured through Medicaid, and standing at 4’5” (53 inches) with a weight of 108 pounds—highlights a moderate risk for obesity-related comorbidities such as type 2 diabetes or metabolic syndrome, particularly given the absence of data indicating physical activity or dietary habits. The undisclosed language preference further complicates risk assessment, as communication barriers may hinder adherence to treatment plans or health literacy. To mitigate risks, targeted interventions should prioritize nutritional counseli[... rest of text is truncated]
6. The 49-year-old Portuguese female presents with a body mass index (BMI) of 43.9, categorizing her as obese, which significantly elevates her risk for comorbidities such as type 2 diabetes, cardiovascular disease, and sleep apnea. Despite a normal blood pressure reading of 112/81 mmHg, her metabolic and cardiovascular health warrant closer monitoring due to the profound impact of severe obesity on systemic physiology. She was admitted through the emergency room under emergent conditions, with a 5-day hospitalization reflecting the acute nature of her presenting issue, though the lack of specificity in her admission diagnosis limits further clinical interpretation. Her Medicaid insurance status may influence access to follow-up care and specialized services, necessitating consideration of cost barriers in any recommended interventions. With four existing medical records, there is evidence of prior healthcare engagement, though the absence of documented language preference raises concerns about potential communi[... rest of text is truncated]
7. The 79-year-old male patient presents with a BMI of 28.6, categorizing him as overweight, which may contribute to increased cardiovascular strain, particularly in conjunction with his systolic blood pressure of 130 mmHg—a value approaching the threshold for hypertension when considered alongside his diastolic reading of 80 mmHg. Admitted through the emergency room under urgent conditions, his 12-day hospital stay suggests a complex or unresolved acute health event, though his medical records indicate no prior documented encounters, raising questions about continuity of care or potential barriers to outpatient services. As a married individual enrolled in Medicare, his demographic profile aligns with populations requiring heightened attention to age-related comorbidities, including those exacerbated by excess weight, such as osteoarthritis or sleep apnea, though his Cape Verdean heritage introduces considerations for genetic predispositions or cultural health practices not explicitly captured in the data. The [... rest of text is truncated]
8. This 81-year-old Black/Cape Verdean woman presents as a complex case at the intersection of geriatric care and chronic disease management. With a body mass index of 26.1—categorizing her as overweight—she exhibits a systolic blood pressure of 110 mmHg paired with a notably low diastolic reading of 62 mmHg, suggesting possible hypoperfusion risks or medication effects in an elderly population. Admitted urgently through the emergency room with no prior medical records on file, her 10-day hospital stay highlights significant acute healthcare utilization without documented continuity of care. The absence of preexisting records raises concerns about unmet primary care needs, compounded by her widowed status, which may indicate social isolation and limited health advocacy. While her BMI signals increased susceptibility to metabolic and cardiovascular comorbidities, her blood pressure profile warrants scrutiny for syncope or falls risk due to potential orthostatic instability. Given her Medicare coverage and demogra[... rest of text is truncated]

**Generate hypotheses**

Generate hypotheses which are predictive of the target variable.

The `selection_method` parameter defines how we compute neuron predictiveness (see `src/select_neurons.py` for more details):
- "separation_score": E[target | top-activating examples] - E[target | zero-activating examples]
- "correlation": pearson(neuron activations, target variable)
- "lasso": select N nonzero features with an L1 regularized model

This cell outputs a dataframe with the following columns:
- `neuron_idx`: The index of the neuron in the SAE (if you're using multiple SAEs, this will be a global index across all of them).
- `source_sae`: The SAE that the neuron was selected from.
- `target_{selection_method}`: The predictiveness of the neuron for the target variable, using the selected `selection_method`.
- `interpretation`: The natural language interpretation of the neuron.
- `interp_fidelity_score`: The F1 fidelity score for how well the neuron's interpretation actually corresponds to its activation pattern.

In [9]:
RESULT_EXTRA_INFO = "50_Hypotheses"

In [10]:
selection_method = "lasso"
multi_class = True  # Set to True for direct multi-class classification, False for using one vs. rest classification
if len(set(labels)) == 2:
    selection_method = "lasso"  # Use logistic regression for binary classification
    multi_class = True
result_dir = f'result_cache/{CACHE_SIGNAL}_one_vs_rest_{RESULT_EXTRA_INFO}' if not multi_class else f'result_cache/{CACHE_SIGNAL}_multi_class_{RESULT_EXTRA_INFO}'

if not os.path.exists(result_dir):
    os.makedirs(result_dir)
if multi_class:
    results = generate_hypotheses(
        texts=texts,
        labels=labels,
        embeddings=embeddings,
        sae=sae_list,
        cache_name=CACHE_NAME,
        selection_method=selection_method,
        n_selected_neurons=50,
        n_candidate_interpretations=30,
        task_specific_instructions=TASK_SPECIFIC_INSTRUCTIONS,
        classification=True,
        interpreter_model="Qwen/Qwen3-32B",
        annotator_model="Qwen/Qwen3-32B",  # Use the same model for both interpretation and annotation
    )

    print("\nMost predictive features of Yelp reviews:")
    pd.set_option('display.max_colwidth', None)
    display(results.sort_values(by=f"target_{selection_method}", ascending=False))
    pd.reset_option('display.max_colwidth')
    results.to_csv(os.path.join(result_dir, f"hypotheses_{selection_method}.csv"), index=False)
else:
    results = {}
    for key in number_dict.keys():
        converted_key = {number_dict[dic_key]: 1 if dic_key == key else 0 for dic_key in number_dict.keys()}
        converted_label = [converted_key[label] for label in labels]
        print(len(converted_label))
        results[f'{key}_vs_rest'] = generate_hypotheses(
            texts=texts,
            labels=converted_label,
            embeddings=embeddings,
            sae=sae_list,
            cache_name=CACHE_NAME,
            selection_method=selection_method,
            n_selected_neurons=15,
            n_candidate_interpretations=3,
            task_specific_instructions=TASK_SPECIFIC_INSTRUCTIONS,
            classification=True,
            n_scoring_examples= 1000,  # Number of examples to use for scoring hypotheses
            interpreter_model="Qwen/Qwen3-32B",
            annotator_model="Qwen/Qwen3-32B",  # Use the same model for both interpretation and annotation
        )
    for key, value in results.items():
        key_norm = key.replace("/", "or")
        key_norm = key_norm.replace(" ", "_")
        print(f"\nMost predictive features of Yelp reviews for {key}:")
        pd.set_option('display.max_colwidth', None)
        display(value.sort_values(by=f"target_{selection_method}", ascending=False))
        pd.reset_option('display.max_colwidth')
        results[key].to_csv(os.path.join(result_dir, f"hypotheses_{key_norm}_{selection_method}.csv"), index=False)

Embeddings shape: (6087, 1024)

Computing activations (batchsize=16384): 100%|██████████| 1/1 [00:00<00:00, 200.78it/s]
Computing activations (batchsize=16384): 100%|██████████| 1/1 [00:00<00:00, 160.57it/s]
Computing activations (batchsize=16384): 100%|██████████| 1/1 [00:00<00:00, 159.26it/s]

Activations shape: (6087, 512)

Step 1: Selecting top 50 predictive neurons
LASSO iteration   L1 Alpha # Features   Time (s)
----------------------------------------

       0   1.00e-01        505       8.24
       1   3.16e+01        161       0.20
       2   5.62e+02          2       0.10
       3   1.33e+02         40       0.13
       4   6.49e+01         93       0.17
       5   9.31e+01         59       0.23
       6   1.11e+02         50       0.13

Found alpha=1.11e+02 yielding exactly 50 features
Total search time: 9.20s

Step 2: Interpreting selected neurons

Generating 30 interpretation(s) per neuron: 100%|██████████| 1500/1500 [04:05<00:00,  6.12it/s]

Step 3: Scoring Interpretations
Found 7022 cached items; annotating 142978 uncached items

Scoring neuron interpretation fidelity (50 neurons; 30 candidate interps per neuron; 100 examples to score each interp): 100%|██████████| 142978/142978 [1:34:39<00:00, 25.17it/s]

Most predictive features of Yelp reviews:

,neuron_idx,source_sae,target_lasso,interpretation,f1_fidelity_score
0,197,"(128, 64)",0.514709,"<think>\n\n</think>\n\n- ""mentions advanced age (80 years or older) in the patient description",1.000000
1,64,"(128, 32)",0.199900,"<think>\n\n</think>\n\n- ""Patient is 91 years old or older and admitted via the emergency room",0.958333
2,166,"(128, 64)",0.194334,"<think>\n\n</think>\n\n- ""Lacks documentation of height, weight, systolic and diastolic blood pressure, and BMI",0.782000
3,457,"(256, 64)",0.145490,"<think>\n\n</think>\n\n- ""Mentions an extended length of stay (typically 10 days or more) combined with missing or incomplete anthropometric data such as weight, height, BMI, or blood pressure readings.",0.898222
4,293,"(256, 64)",0.143006,"<think>\n\n</think>\n\n- ""Admitted via physician referral and had a prolonged or complex hospital stay (longer than expected for the admission type)",0.786835
5,137,"(128, 64)",0.141077,"<think>\n\n</think>\n\n- ""Mentions systolic blood pressure in the normal or elevated range (e.g., 120-160 mmHg) in the context of elderly patients (age 80+), often highlighting concerns",0.744304
6,345,"(256, 64)",0.112838,"<think>\n\n</think>\n\n- ""Mentions that the patient was admitted via transfer from another hospital",1.000000
7,263,"(256, 64)",0.093863,"<think>\n\n</think>\n\n- ""The text includes recorded systolic and diastolic blood pressure values that fall within the normal or borderline elevated range (≤129 mmHg systolic and ≤84 mmHg diastolic), without",0.657576
8,138,"(128, 64)",0.085225,"<think>\n\n</think>\n\n- ""Mentions both systolic and diastolic blood pressure values with specific numerical readings",0.642462
9,248,"(128, 64)",0.083127,"<think>\n\n</think>\n\n- ""The patient is between 60 and 69 years old.",1.000000
10,32,"(128, 32)",0.082055,"<think>\n\n</think>\n\n- ""Mentions prolonged hospitalization (typically 3 days or more) following an emergency room admission, often highlighting complex care needs or acute decompensation in the context of limited or no prior medical records.",0.642353
11,60,"(128, 32)",0.080251,"<think>\n\n</think>\n\n- ""Mentions blood pressure readings that indicate prehypertension or stage 1 hypertension according to clinical guidelines",0.839524
12,167,"(128, 64)",0.079842,"<think>\n\n</think>\n\n- ""mentions internal transfer to or from a psychiatric unit",1.000000
13,438,"(256, 64)",0.075251,"<think>\n\n</think>\n\n- ""The text mentions that the patient's admission type is 'urgent' and was facilitated through a physician referral, with a brief hospital stay (typically 2–3 days) and an absence or minimal presence of prior medical records",0.838095
14,358,"(256, 64)",0.065118,"<think>\n\n</think>\n\n- ""The text indicates that this is the patient’s first documented healthcare encounter, as evidenced by the explicit mention of 'no prior medical records,' 'first documented interaction,' or 'initial documented engagement' with the healthcare system.",0.916087
15,503,"(256, 64)",0.058761,"<think>\n\n</think>\n\n- ""mentions a patient age between 18 and 22 years old",0.823529
16,16,"(128, 32)",0.056451,"<think>\n\n</think>\n\n- ""Mentions the absence of recorded blood pressure, BMI, weight, and height, indicating gaps in vital sign and anthropometric data.",0.896000
17,114,"(128, 32)",0.056028,"<think>\n\n</think>\n\n- ""The text mentions the patient is a young adult (18–21 years old) with limited or no prior medical records and missing baseline vital signs such as blood pressure, BMI, height, and weight.",0.989899
18,112,"(128, 32)",0.052190,"<think>\n\n</think>\n\n- ""Admission was facilitated by a physician referral",0.979592
19,334,"(256, 64)",0.051387,"<think>\n\n</think>\n\n- ""The text describes a young adult (age 18-24) with no prior medical records and missing vital signs such as blood pressure, BMI, height, and weight, admitted urgently or emergently for a short",0.876404
20,131,"(128, 64)",0.048742,"<think>\n\n</think>\n\n- ""Mentions that key clinical metrics such as weight, height, blood pressure, and BMI are unknown or unrecorded, which limits a comprehensive assessment of the patient's health status.",0.648615
21,401,"(256, 64)",0.041100,"<think>\n\n</think>\n\n- ""Mentions patients aged 80 years or older with documented systolic and/or diastolic blood pressure readings and a known or calculable BMI, often highlighting geriatric risk factors such as frailty, falls, or",0.949895
22,309,"(256, 64)",0.038614,"<think>\n\n</think>\n\n- ""Mentions a recent emergency room admission or emergency admission type with a hospital stay, coupled with specific BMI categories (overweight, obese, or underweight) and limited prior medical records, suggesting a pattern of reactive healthcare utilization",0.648615
23,292,"(256, 64)",0.035966,"<think>\n\n</think>\n\n- ""Lacks documented values for systolic and diastolic blood pressure, BMI, height, and weight",0.696216
24,104,"(128, 32)",0.032757,"<think>\n\n</think>\n\n- ""The text mentions the absence of recorded systolic and diastolic blood pressure, BMI, height, or weight data, indicating incomplete baseline health metrics.",0.754286
25,413,"(256, 64)",0.030481,"<think>\n\n</think>\n\n- ""Mentions isolated systolic hypertension (elevated systolic blood pressure with normal diastolic blood pressure)",0.958333
26,432,"(256, 64)",0.030025,"<think>\n\n</think>\n\n- ""Mentions blood pressure readings with diastolic values at or below 60 mmHg",0.938298
27,394,"(256, 64)",0.028457,"<think>\n\n</think>\n\n- ""mentions 'number_of_records: 0' or 'no prior healthcare records'",0.637500
28,82,"(128, 32)",0.024966,"<think>\n\n</think>\n\n- ""Mentions systolic blood pressure in the Stage 1 hypertension range (≥130 and <140 mmHg) or diastolic blood pressure in the Stage 1 hypertension range (≥80",0.989899
29,207,"(128, 64)",0.023566,"<think>\n\n</think>\n\n- ""Mentions patients aged 70 to 79 years with normal BMI and blood pressure readings indicating prehypertension or early cardiovascular risk, often highlighting the need for monitoring or preventive care due to age-related vulnerabilities.",0.907253
30,278,"(256, 64)",0.018666,"<think>\n\n</think>\n\n- ""The text mentions that systolic and diastolic blood pressure, BMI, height, and weight are unrecorded or missing, leading to a lack of baseline health metrics.",0.859535
31,177,"(128, 64)",0.017366,"<think>\n\n</think>\n\n- ""The text does not contain recorded values for height, weight, blood pressure, or BMI.",0.939574
32,173,"(128, 64)",0.017319,"<think>\n\n</think>\n\n- ""The text mentions a normal BMI (18.5–24.9) and blood pressure within the optimal or normal range, and indicates that this is the patient's first recorded healthcare encounter (zero prior medical records",0.947368
33,243,"(128, 64)",0.015937,"<think>\n\n</think>\n\n- ""Mentions internal transfer to or from a psychiatric unit in the context of urgent admission",0.989899
34,343,"(256, 64)",0.015123,"<think>\n\n</think>\n\n- ""The text lacks recorded values for weight, height, systolic blood pressure, diastolic blood pressure, and body mass index (BMI), resulting in an absence of baseline biometric and cardiovascular health data.",0.840471
35,494,"(256, 64)",0.013463,"<think>\n\n</think>\n\n- ""The text includes the phrase 'admitted urgently via physician referral' or 'admitted via the emergency room under urgent conditions' and mentions a 3-day (or similar short-term) hospital stay, while also stating that",0.806914
36,180,"(128, 64)",0.011140,"<think>\n\n</think>\n\n- ""mentions 'divorced' marital status and lacks documented systolic and diastolic blood pressure values",0.924731
37,468,"(256, 64)",0.010594,"<think>\n\n</think>\n\n- ""Mentions a patient age between 40 and 60 years old",0.792000
38,140,"(128, 64)",0.009028,"<think>\n\n</think>\n\n- ""Mentions hypotension with specific systolic and diastolic blood pressure readings below normal thresholds (systolic < 120 mmHg and diastolic < 60 mmHg), particularly",1.000000
39,35,"(128, 32)",0.009008,"<think>\n\n</think>\n\n- ""Mentions elevated systolic blood pressure (≥130 mmHg) without recording height, leading to an uncalculated or unassessable BMI.",0.876404
40,46,"(128, 32)",0.008507,"<think>\n\n</think>\n\n- ""Absence of documented systolic and diastolic blood pressure readings",0.938298
41,157,"(128, 64)",0.008182,"<think>\n\n</think>\n\n- ""Admitted from a skilled nursing facility and has a recorded hospital length of stay",1.000000
42,399,"(256, 64)",0.007447,"<think>\n\n</think>\n\n- ""Mentions missing or incomplete documentation of systolic and diastolic blood pressure, BMI, height, and weight, indicating a lack of recorded baseline health metrics",0.706849
43,435,"(256, 64)",0.006716,"<think>\n\n</think>\n\n- ""mentions systolic blood pressure in the elevated range (≥130 mmHg) or diastolic blood pressure in the elevated range (≥80 mmHg), indicating stage 1 or stage 2",0.888989
44,506,"(256, 64)",0.005876,"<think>\n\n</think>\n\n- ""Mentions both systolic and diastolic blood pressure values in the same sentence, often highlighting their clinical significance or relationship to health conditions.",0.726575
45,246,"(128, 64)",0.003716,"<think>\n\n</think>\n\n- ""Mentions both systolic and diastolic blood pressure readings, with at least one reading indicating elevated or abnormal values (e.g., prehypertension, hypertension, or unknown readings highlighting gaps in cardiovascular data)",0.562759
46,323,"(256, 64)",0.003158,"<think>\n\n</think>\n\n- ""The patient is male and belongs to a demographic group with elevated risks for hypertension and cardiovascular disease, as explicitly mentioned in the text.",0.892889
47,13,"(128, 32)",0.001327,"<think>\n\n</think>\n\n- ""Mentions a prolonged length of stay (generally 10 days or more) in the context of an emergency room admission",0.799500
48,373,"(256, 64)",0.001305,"<think>\n\n</think>\n\n- ""The text mentions the absence or unrecorded status of BMI, systolic and diastolic blood pressure, height, and weight, highlighting significant gaps in baseline clinical metrics that hinder a comprehensive health assessment.",0.856092
49,170,"(128, 64)",0.001050,"<think>\n\n</think>\n\n- ""Mentions psychiatric care transfers or admissions (e.g., internal transfer to or from psychiatric services, urgent admission linked to psychiatric care)",0.630137

**Save all in one json**

In [20]:
import os
import json
result_dir = f'result_cache/{CACHE_SIGNAL}_{RESULT_EXTRA_INFO}'
if not os.path.isdir(result_dir):
    os.makedirs(result_dir)
train_all_info_file = os.path.join(result_dir, "train_all_info.jsonl")
test_all_info_file = os.path.join(result_dir, "test_all_info.jsonl")
with open(test_all_info_file, 'w') as f:
    for text, label, idx in zip(test_texts, test_y, range(len(test_texts))):
        f.write(json.dumps({"idx": idx, "profile": text, "label": label}) + "\n")
with open(train_all_info_file, 'w') as f:
    for text, label, idx in zip(texts, labels, range(len(texts))):
        f.write(json.dumps({"idx": idx, "profile": text, "label": label}) + "\n")

In [ ]:
from hypothesaes.sae import SparseAutoencoder, load_model, get_multiple_sae_activations, get_sae_checkpoint_name
activations, neuron_source_sae_info = get_multiple_sae_activations(sae_list, test_embeddings, return_neuron_source_info=True)

Computing activations (batchsize=16384): 100%|██████████| 1/1 [00:00<00:00, 164.64it/s]
Computing activations (batchsize=16384): 100%|██████████| 1/1 [00:00<00:00, 227.88it/s]
Computing activations (batchsize=16384): 100%|██████████| 1/1 [00:00<00:00, 244.15it/s]

In [22]:
def clean_interpretation(text):
    return text.replace("<think>", "").replace("</think>", "").strip().lstrip("-").strip().strip('"')

# 创建解释字典
if multi_class:
    neuron_interpretations = {
        row['neuron_idx']: clean_interpretation(row['interpretation'])
        for _, row in results.iterrows()
    }
else:
    neuron_interpretations = {}
    for key, value in results.items():
        neuron_interpretations[key] = {
            row['neuron_idx']: clean_interpretation(row['interpretation'])
            for _, row in value.iterrows()
        }

In [23]:
import torch
def describe_from_activations(activations: np.array, neuron_interpretations: dict, threshold=0.5, extra_info =None):
    """根据 activation 向量和解释字典，返回解释列表"""

    
    descriptions = []
    for idx, value in enumerate(activations):
        if value.item() > threshold and idx in neuron_interpretations:
            if extra_info is not None:
                descriptions.append((idx, neuron_interpretations[idx], value.item(), extra_info))
            else:
                descriptions.append((idx, neuron_interpretations[idx], value.item()))
    
    # 可以按激活值排序
    descriptions = sorted(descriptions, key=lambda x: -x[2])
    return descriptions
def render_descriptions(descriptions, multiclass=False):
    if not descriptions:
        return "No meaningful activations found."

    output = ["This text likely involves:"]
    if multiclass:   
        for idx, interp, score in descriptions:
            output.append(f"- {interp} (activation={score:.2f})")
    else:
        for idx, interp, score, type in descriptions:
            output.append(f"- {interp} (activation={score:.2f}, type={type})")
    return "\n".join(output)

In [ ]:
interpret_list = []
if multi_class:
    for act in activations:
        descriptions = describe_from_activations(act, neuron_interpretations, threshold=0)
        interpret_list.append(render_descriptions(descriptions, True))
else:
    for act in activations:
        descriptions = []
        for key, value in neuron_interpretations.items():
            descriptions.extend(describe_from_activations(act, value, threshold=0, extra_info=f'[{key}]'))
        interpret_list.append(render_descriptions(descriptions, False))
with open(os.path.join(result_dir, 'test_interpretations.jsonl'), "w") as f:
    for text, interpret in zip(range(len(interpret_list)), interpret_list):
        f.write(json.dumps({"text": text, "interpretation": interpret}) + "\n")

**Evaluate held-out generalization**

Finally, we evaluate whether these are good hypotheses by testing whether their natural language interpretations can predict the target variable.  

We compute annotations for each hypothesized concept on a holdout set (not seen during SAE training & feature selection).

After annotation, we output a dataframe with the following columns:
- `hypothesis`: The natural language hypothesis (which came from interpreting a predictive neuron in the SAE)
- `separation_score`: How much the target variable differs when the concept is present vs. absent (i.e., $E[Y\mid\text{concept} = 1] - E[Y\mid\text{concept} = 0]$).
- `separation_pvalue`: The t-test p-value of the null hypothesis that the separation score is 0 (i.e., the concept is not associated with the target variable).
- `regression_coef`: The coefficient of the concept in a multivariate linear regression of the target variable on all concepts.
- `regression_pval`: The p-value of the null hypothesis that the regression coefficient is 0.
- `feature_prevalence`: The fraction of examples that contain the concept.

Additionally, we output the evaluation metrics used in the paper:
- Significant hypotheses: the number of hypotheses that are significant in the multivariate regression at a specified significance level (default $0.1$) after Bonferroni correction. You can pass in a different significance level using the `corrected_pval_threshold` parameter.
- AUC or $R^2$: how well the hypotheses collectively predict the target variable in the multivariate regression.

In [16]:
# holdout_df = pd.read_json(os.path.join(base_dir, "yelp-demo-holdout-2K.json"), lines=True)
# holdout_texts = holdout_df['text'].tolist()
# holdout_labels = holdout_df['stars'].values
from hypothesaes.quickstart import evaluate_hypotheses
if multi_class:
    metrics, evaluation_df = evaluate_hypotheses(
        hypotheses_df=results,
        texts=test_texts,
        labels=label_test,
        cache_name=CACHE_NAME,
        max_words_per_example=1024,
        annotator_model="Qwen/Qwen3-32B",  # Use the same model as for training
        classification=True
    )

    pd.set_option('display.max_colwidth', None)
    display(evaluation_df)
    pd.reset_option('display.max_colwidth')

    print("\nHoldout Set Metrics:")
    print(f"R² Score: {metrics['r2']:.3f}")
    print(f"Significant hypotheses: {metrics['Significant'][0]}/{metrics['Significant'][1]} " 
        f"(p < {metrics['Significant'][2]:.3e})")
else:
    metrics, evaluation_df = {}, {}
    for key in number_dict.keys():
        key_norm = key.replace("/", "or")
        key_norm = key_norm.replace(" ", "_")
        converted_key = {number_dict[dic_key]: 1 if dic_key == key else 0 for dic_key in number_dict.keys()}
        converted_label = [converted_key[label] for label in label_test]
        metrics[key], evaluation_df[key] = evaluate_hypotheses(
            hypotheses_df=results[f'{key}_vs_rest'],
            texts=test_texts,
            labels=converted_label,
            cache_name=os.path.join(CACHE_NAME, CACHE_SIGNAL, f"{key}_vs_rest"),
            max_words_per_example=1024,
            annotator_model="Qwen/Qwen3-32B",  # Use the same model as for training
            classification=True
        )
        evaluation_df[key].to_csv(os.path.join(result_dir, f"evaluation_{key_norm}.csv"), index=False)
        with open(os.path.join(result_dir, f"metrics_{key_norm}.json"), "w") as f:
            json.dump(metrics[key], f, indent=4)
        pd.set_option('display.max_colwidth', None)
        display(evaluation_df[key])
        pd.reset_option('display.max_colwidth')
        print(f"\nHoldout Set Metrics for {key}:")
        print(f"R² Score: {metrics[key]['r2']:.3f}")
        print(f"Significant hypotheses: {metrics[key]['Significant'][0]}/{metrics[key]['Significant'][1]} " 
            f"(p < {metrics[key]['Significant'][2]:.3e})")

Step 1: Annotating texts with 50 hypotheses
Found 714 cached items; annotating 17136 uncached items

Annotating:  73%|███████▎  | 12448/17136 [08:48<03:06, 25.08it/s]

API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)
API error: Request timed out.; retrying in 10.0s... (2/3)

Annotating: 100%|██████████| 17136/17136 [12:37<00:00, 22.62it/s]

Step 2: Computing predictiveness of hypothesis annotations
Optimization terminated successfully.
         Current function value: 0.485686
         Iterations 7

,hypothesis,separation_score,separation_pval,regression_coef,regression_pval,feature_prevalence
12,"<think>\n\n</think>\n\n- ""mentions internal transfer to or from a psychiatric unit",0.334758,1.044825e-01,3.065696,NaN,0.016807
33,"<think>\n\n</think>\n\n- ""Mentions internal transfer to or from a psychiatric unit in the context of urgent admission",0.334758,1.044825e-01,3.065696,NaN,0.016807
17,"<think>\n\n</think>\n\n- ""The text mentions the patient is a young adult (18–21 years old) with limited or no prior medical records and missing baseline vital signs such as blood pressure, BMI, height, and weight.",0.237720,3.078827e-02,0.989568,0.297442,0.061625
13,"<think>\n\n</think>\n\n- ""The text mentions that the patient's admission type is 'urgent' and was facilitated through a physician referral, with a brief hospital stay (typically 2–3 days) and an absence or minimal presence of prior medical records",0.167584,5.193572e-03,0.392470,0.368766,0.263305
14,"<think>\n\n</think>\n\n- ""The text indicates that this is the patient’s first documented healthcare encounter, as evidenced by the explicit mention of 'no prior medical records,' 'first documented interaction,' or 'initial documented engagement' with the healthcare system.",0.165348,1.719629e-03,1.181885,0.000993,0.495798
15,"<think>\n\n</think>\n\n- ""mentions a patient age between 18 and 22 years old",0.163842,5.732042e-01,0.921543,0.678133,0.008403
32,"<think>\n\n</think>\n\n- ""The text mentions a normal BMI (18.5–24.9) and blood pressure within the optimal or normal range, and indicates that this is the patient's first recorded healthcare encounter (zero prior medical records",0.148887,5.305619e-02,0.286397,0.580962,0.137255
37,"<think>\n\n</think>\n\n- ""Mentions a patient age between 40 and 60 years old",0.146965,1.255471e-02,0.017916,0.963187,0.280112
7,"<think>\n\n</think>\n\n- ""The text includes recorded systolic and diastolic blood pressure values that fall within the normal or borderline elevated range (≤129 mmHg systolic and ≤84 mmHg diastolic), without",0.145628,9.543630e-03,0.044932,0.926766,0.330532
19,"<think>\n\n</think>\n\n- ""The text describes a young adult (age 18-24) with no prior medical records and missing vital signs such as blood pressure, BMI, height, and weight, admitted urgently or emergently for a short",0.144315,2.910959e-01,-0.668369,0.535853,0.039216
27,"<think>\n\n</think>\n\n- ""mentions 'number_of_records: 0' or 'no prior healthcare records'",0.094962,1.426321e-01,0.078352,0.849265,0.212885
35,"<think>\n\n</think>\n\n- ""The text includes the phrase 'admitted urgently via physician referral' or 'admitted via the emergency room under urgent conditions' and mentions a 3-day (or similar short-term) hospital stay, while also stating that",0.083521,1.714674e-01,-0.393914,0.342678,0.252101
22,"<think>\n\n</think>\n\n- ""Mentions a recent emergency room admission or emergency admission type with a hospital stay, coupled with specific BMI categories (overweight, obese, or underweight) and limited prior medical records, suggesting a pattern of reactive healthcare utilization",0.041619,4.367366e-01,0.006339,0.985161,0.563025
26,"<think>\n\n</think>\n\n- ""Mentions blood pressure readings with diastolic values at or below 60 mmHg",0.036585,6.604249e-01,0.516687,0.426243,0.114846
38,"<think>\n\n</think>\n\n- ""Mentions hypotension with specific systolic and diastolic blood pressure readings below normal thresholds (systolic < 120 mmHg and diastolic < 60 mmHg), particularly",0.026471,8.318819e-01,-0.079238,0.922472,0.047619
9,"<think>\n\n</think>\n\n- ""The patient is between 60 and 69 years old.",0.013919,8.406557e-01,-0.482882,0.220250,0.179272
36,"<think>\n\n</think>\n\n- ""mentions 'divorced' marital status and lacks documented systolic and diastolic blood pressure values",-0.004451,9.692525e-01,0.650307,0.263268,0.056022
30,"<think>\n\n</think>\n\n- ""The text mentions that systolic and diastolic blood pressure, BMI, height, and weight are unrecorded or missing, leading to a lack of baseline health metrics.",-0.006173,9.136981e-01,2.483109,0.033913,0.319328
24,"<think>\n\n</think>\n\n- ""The text mentions the absence of recorded systolic and diastolic blood pressure, BMI, height, or weight data, indicating incomplete baseline health metrics.",-0.024553,6.520580e-01,1.086199,0.227524,0.389356
40,"<think>\n\n</think>\n\n- ""Absence of documented systolic and diastolic blood pressure readings",-0.030260,5.744531e-01,-1.118633,0.171448,0.414566
18,"<think>\n\n</think>\n\n- ""Admission was facilitated by a physician referral",-0.032575,5.730226e-01,-0.835962,0.049412,0.302521
34,"<think>\n\n</think>\n\n- ""The text lacks recorded values for weight, height, systolic blood pressure, diastolic blood pressure, and body mass index (BMI), resulting in an absence of baseline biometric and cardiovascular health data.",-0.039364,4.969164e-01,1.051919,0.208921,0.299720
23,"<think>\n\n</think>\n\n- ""Lacks documented values for systolic and diastolic blood pressure, BMI, height, and weight",-0.044252,4.328999e-01,-1.454755,0.142231,0.330532
8,"<think>\n\n</think>\n\n- ""Mentions both systolic and diastolic blood pressure values with specific numerical readings",-0.054747,3.192811e-01,0.055806,0.907622,0.369748
42,"<think>\n\n</think>\n\n- ""Mentions missing or incomplete documentation of systolic and diastolic blood pressure, BMI, height, and weight, indicating a lack of recorded baseline health metrics",-0.058563,2.720792e-01,0.573755,0.482637,0.450980
31,"<think>\n\n</think>\n\n- ""The text does not contain recorded values for height, weight, blood pressure, or BMI.",-0.066667,2.522254e-01,-0.112083,0.925705,0.294118
48,"<think>\n\n</think>\n\n- ""The text mentions the absence or unrecorded status of BMI, systolic and diastolic blood pressure, height, and weight, highlighting significant gaps in baseline clinical metrics that hinder a comprehensive health assessment.",-0.072401,2.099221e-01,-0.847005,0.481546,0.302521
16,"<think>\n\n</think>\n\n- ""Mentions the absence of recorded blood pressure, BMI, weight, and height, indicating gaps in vital sign and anthropometric data.",-0.079626,1.498335e-01,-0.531485,0.572769,0.358543
44,"<think>\n\n</think>\n\n- ""Mentions both systolic and diastolic blood pressure values in the same sentence, often highlighting their clinical significance or relationship to health conditions.",-0.082563,1.261476e-01,0.116303,0.785656,0.406162
20,"<think>\n\n</think>\n\n- ""Mentions that key clinical metrics such as weight, height, blood pressure, and BMI are unknown or unrecorded, which limits a comprehensive assessment of the patient's health status.",-0.085017,1.221899e-01,-0.565943,0.572254,0.366947
28,"<think>\n\n</think>\n\n- ""Mentions systolic blood pressure in the Stage 1 hypertension range (≥130 and <140 mmHg) or diastolic blood pressure in the Stage 1 hypertension range (≥80",-0.118312,4.616739e-02,0.819716,0.324280,0.274510
6,"<think>\n\n</think>\n\n- ""Mentions that the patient was admitted via transfer from another hospital",-0.119521,7.175396e-02,-0.604717,0.158538,0.198880
4,"<think>\n\n</think>\n\n- ""Admitted via physician referral and had a prolonged or complex hospital stay (longer than expected for the admission type)",-0.123414,2.610446e-02,0.218754,0.595434,0.350140
46,"<think>\n\n</think>\n\n- ""The patient is male and belongs to a demographic group with elevated risks for hypertension and cardiovascular disease, as explicitly mentioned in the text.",-0.126869,2.061093e-02,-0.520890,0.077420,0.369748
11,"<think>\n\n</think>\n\n- ""Mentions blood pressure readings that indicate prehypertension or stage 1 hypertension according to clinical guidelines",-0.129412,2.716509e-02,0.015154,0.985125,0.285714
45,"<think>\n\n</think>\n\n- ""Mentions both systolic and diastolic blood pressure readings, with at least one reading indicating elevated or abnormal values (e.g., prehypertension, hypertension, or unknown readings highlighting gaps in cardiovascular data)",-0.131832,1.563464e-02,-0.381639,0.217828,0.378151
41,"<think>\n\n</think>\n\n- ""Admitted from a skilled nursing facility and has a recorded hospital length of stay",-0.132163,4.611709e-01,0.769371,0.492503,0.022409
2,"<think>\n\n</think>\n\n- ""Lacks documentation of height, weight, systolic and diastolic blood pressure, and BMI",-0.134851,1.463271e-02,-2.183055,0.005567,0.355742
43,"<think>\n\n</think>\n\n- ""mentions systolic blood pressure in the elevated range (≥130 mmHg) or diastolic blood pressure in the elevated range (≥80 mmHg), indicating stage 1 or stage 2",-0.135540,2.026890e-02,-1.193213,0.020995,0.288515
49,"<think>\n\n</think>\n\n- ""Mentions psychiatric care transfers or admissions (e.g., internal transfer to or from psychiatric services, urgent admission linked to psychiatric care)",-0.158824,2.022553e-01,-2.815566,0.049319,0.047619
10,"<think>\n\n</think>\n\n- ""Mentions prolonged hospitalization (typically 3 days or more) following an emergency room admission, often highlighting complex care needs or acute decompensation in the context of limited or no prior medical records.",-0.171189,1.169367e-03,-0.641349,0.047976,0.512605
5,"<think>\n\n</think>\n\n- ""Mentions systolic blood pressure in the normal or elevated range (e.g., 120-160 mmHg) in the context of elderly patients (age 80+), often highlighting concerns",-0.200676,2.077660e-02,1.299349,0.049686,0.103641
29,"<think>\n\n</think>\n\n- ""Mentions patients aged 70 to 79 years with normal BMI and blood pressure readings indicating prehypertension or early cardiovascular risk, often highlighting the need for monitoring or preventive care due to age-related vulnerabilities.",-0.213109,6.378250e-03,-1.175635,0.015322,0.131653
39,"<think>\n\n</think>\n\n- ""Mentions elevated systolic blood pressure (≥130 mmHg) without recording height, leading to an uncalculated or unassessable BMI.",-0.227405,9.581183e-02,0.143234,0.895238,0.039216
25,"<think>\n\n</think>\n\n- ""Mentions isolated systolic hypertension (elevated systolic blood pressure with normal diastolic blood pressure)",-0.245550,1.488337e-03,-1.099020,0.046864,0.134454
0,"<think>\n\n</think>\n\n- ""mentions advanced age (80 years or older) in the patient description",-0.289964,1.562159e-05,-0.216267,0.849675,0.187675
21,"<think>\n\n</think>\n\n- ""Mentions patients aged 80 years or older with documented systolic and/or diastolic blood pressure readings and a known or calculable BMI, often highlighting geriatric risk factors such as frailty, falls, or",-0.291759,2.830865e-05,-1.493701,0.191523,0.170868
3,"<think>\n\n</think>\n\n- ""Mentions an extended length of stay (typically 10 days or more) combined with missing or incomplete anthropometric data such as weight, height, BMI, or blood pressure readings.",-0.342560,3.850099e-06,-0.524999,0.533818,0.145658
47,"<think>\n\n</think>\n\n- ""Mentions a prolonged length of stay (generally 10 days or more) in the context of an emergency room admission",-0.345623,7.376688e-07,-1.596218,0.037052,0.168067
1,"<think>\n\n</think>\n\n- ""Patient is 91 years old or older and admitted via the emergency room",-0.450437,9.061827e-04,-2.172962,0.099937,0.039216

Holdout Set Metrics:
R² Score: 0.299
Significant hypotheses: 1/50 (p < 2.000e-03)

In [17]:
if multi_class:
        pd.set_option('display.max_colwidth', None)
        display(evaluation_df)
        pd.reset_option('display.max_colwidth')
        print("\nHoldout Set Metrics:")
        print(f"R² Score: {metrics['r2']:.3f}")
        print(f"Significant hypotheses: {metrics['Significant'][0]}/{metrics['Significant'][1]} " 
            f"(p < {metrics['Significant'][2]:.3e})")
        evaluation_df.to_csv(os.path.join(result_dir, "evaluation.csv"), index=False)
        with open(os.path.join(result_dir, "metrics.json"), "w") as f:
            json.dump(metrics, f, indent=4)
        
else:
        for key in metrics.keys():
                # print(metrics[key])
                pd.set_option('display.max_colwidth', None)
                display(evaluation_df[key])
                pd.reset_option('display.max_colwidth')
                print(f"\nHoldout Set Metrics for {key}:")
                print(f"R² Score: {metrics[key]['r2']:.3f}")
                print(f"Significant hypotheses: {metrics[key]['Significant'][0]}/{metrics[key]['Significant'][1]} " 
                f"(p < {metrics[key]['Significant'][2]:.3e})")
                evaluation_df[key].to_csv(os.path.join(result_dir, f"evaluation_{key}.csv"), index=False)
                with open(os.path.join(result_dir, f"metrics_{key}.json"), "w") as f:
                    json.dump(metrics[key], f, indent=4)

,hypothesis,separation_score,separation_pval,regression_coef,regression_pval,feature_prevalence
12,"<think>\n\n</think>\n\n- ""mentions internal transfer to or from a psychiatric unit",0.334758,1.044825e-01,3.065696,NaN,0.016807
33,"<think>\n\n</think>\n\n- ""Mentions internal transfer to or from a psychiatric unit in the context of urgent admission",0.334758,1.044825e-01,3.065696,NaN,0.016807
17,"<think>\n\n</think>\n\n- ""The text mentions the patient is a young adult (18–21 years old) with limited or no prior medical records and missing baseline vital signs such as blood pressure, BMI, height, and weight.",0.237720,3.078827e-02,0.989568,0.297442,0.061625
13,"<think>\n\n</think>\n\n- ""The text mentions that the patient's admission type is 'urgent' and was facilitated through a physician referral, with a brief hospital stay (typically 2–3 days) and an absence or minimal presence of prior medical records",0.167584,5.193572e-03,0.392470,0.368766,0.263305
14,"<think>\n\n</think>\n\n- ""The text indicates that this is the patient’s first documented healthcare encounter, as evidenced by the explicit mention of 'no prior medical records,' 'first documented interaction,' or 'initial documented engagement' with the healthcare system.",0.165348,1.719629e-03,1.181885,0.000993,0.495798
15,"<think>\n\n</think>\n\n- ""mentions a patient age between 18 and 22 years old",0.163842,5.732042e-01,0.921543,0.678133,0.008403
32,"<think>\n\n</think>\n\n- ""The text mentions a normal BMI (18.5–24.9) and blood pressure within the optimal or normal range, and indicates that this is the patient's first recorded healthcare encounter (zero prior medical records",0.148887,5.305619e-02,0.286397,0.580962,0.137255
37,"<think>\n\n</think>\n\n- ""Mentions a patient age between 40 and 60 years old",0.146965,1.255471e-02,0.017916,0.963187,0.280112
7,"<think>\n\n</think>\n\n- ""The text includes recorded systolic and diastolic blood pressure values that fall within the normal or borderline elevated range (≤129 mmHg systolic and ≤84 mmHg diastolic), without",0.145628,9.543630e-03,0.044932,0.926766,0.330532
19,"<think>\n\n</think>\n\n- ""The text describes a young adult (age 18-24) with no prior medical records and missing vital signs such as blood pressure, BMI, height, and weight, admitted urgently or emergently for a short",0.144315,2.910959e-01,-0.668369,0.535853,0.039216
27,"<think>\n\n</think>\n\n- ""mentions 'number_of_records: 0' or 'no prior healthcare records'",0.094962,1.426321e-01,0.078352,0.849265,0.212885
35,"<think>\n\n</think>\n\n- ""The text includes the phrase 'admitted urgently via physician referral' or 'admitted via the emergency room under urgent conditions' and mentions a 3-day (or similar short-term) hospital stay, while also stating that",0.083521,1.714674e-01,-0.393914,0.342678,0.252101
22,"<think>\n\n</think>\n\n- ""Mentions a recent emergency room admission or emergency admission type with a hospital stay, coupled with specific BMI categories (overweight, obese, or underweight) and limited prior medical records, suggesting a pattern of reactive healthcare utilization",0.041619,4.367366e-01,0.006339,0.985161,0.563025
26,"<think>\n\n</think>\n\n- ""Mentions blood pressure readings with diastolic values at or below 60 mmHg",0.036585,6.604249e-01,0.516687,0.426243,0.114846
38,"<think>\n\n</think>\n\n- ""Mentions hypotension with specific systolic and diastolic blood pressure readings below normal thresholds (systolic < 120 mmHg and diastolic < 60 mmHg), particularly",0.026471,8.318819e-01,-0.079238,0.922472,0.047619
9,"<think>\n\n</think>\n\n- ""The patient is between 60 and 69 years old.",0.013919,8.406557e-01,-0.482882,0.220250,0.179272
36,"<think>\n\n</think>\n\n- ""mentions 'divorced' marital status and lacks documented systolic and diastolic blood pressure values",-0.004451,9.692525e-01,0.650307,0.263268,0.056022
30,"<think>\n\n</think>\n\n- ""The text mentions that systolic and diastolic blood pressure, BMI, height, and weight are unrecorded or missing, leading to a lack of baseline health metrics.",-0.006173,9.136981e-01,2.483109,0.033913,0.319328
24,"<think>\n\n</think>\n\n- ""The text mentions the absence of recorded systolic and diastolic blood pressure, BMI, height, or weight data, indicating incomplete baseline health metrics.",-0.024553,6.520580e-01,1.086199,0.227524,0.389356
40,"<think>\n\n</think>\n\n- ""Absence of documented systolic and diastolic blood pressure readings",-0.030260,5.744531e-01,-1.118633,0.171448,0.414566
18,"<think>\n\n</think>\n\n- ""Admission was facilitated by a physician referral",-0.032575,5.730226e-01,-0.835962,0.049412,0.302521
34,"<think>\n\n</think>\n\n- ""The text lacks recorded values for weight, height, systolic blood pressure, diastolic blood pressure, and body mass index (BMI), resulting in an absence of baseline biometric and cardiovascular health data.",-0.039364,4.969164e-01,1.051919,0.208921,0.299720
23,"<think>\n\n</think>\n\n- ""Lacks documented values for systolic and diastolic blood pressure, BMI, height, and weight",-0.044252,4.328999e-01,-1.454755,0.142231,0.330532
8,"<think>\n\n</think>\n\n- ""Mentions both systolic and diastolic blood pressure values with specific numerical readings",-0.054747,3.192811e-01,0.055806,0.907622,0.369748
42,"<think>\n\n</think>\n\n- ""Mentions missing or incomplete documentation of systolic and diastolic blood pressure, BMI, height, and weight, indicating a lack of recorded baseline health metrics",-0.058563,2.720792e-01,0.573755,0.482637,0.450980
31,"<think>\n\n</think>\n\n- ""The text does not contain recorded values for height, weight, blood pressure, or BMI.",-0.066667,2.522254e-01,-0.112083,0.925705,0.294118
48,"<think>\n\n</think>\n\n- ""The text mentions the absence or unrecorded status of BMI, systolic and diastolic blood pressure, height, and weight, highlighting significant gaps in baseline clinical metrics that hinder a comprehensive health assessment.",-0.072401,2.099221e-01,-0.847005,0.481546,0.302521
16,"<think>\n\n</think>\n\n- ""Mentions the absence of recorded blood pressure, BMI, weight, and height, indicating gaps in vital sign and anthropometric data.",-0.079626,1.498335e-01,-0.531485,0.572769,0.358543
44,"<think>\n\n</think>\n\n- ""Mentions both systolic and diastolic blood pressure values in the same sentence, often highlighting their clinical significance or relationship to health conditions.",-0.082563,1.261476e-01,0.116303,0.785656,0.406162
20,"<think>\n\n</think>\n\n- ""Mentions that key clinical metrics such as weight, height, blood pressure, and BMI are unknown or unrecorded, which limits a comprehensive assessment of the patient's health status.",-0.085017,1.221899e-01,-0.565943,0.572254,0.366947
28,"<think>\n\n</think>\n\n- ""Mentions systolic blood pressure in the Stage 1 hypertension range (≥130 and <140 mmHg) or diastolic blood pressure in the Stage 1 hypertension range (≥80",-0.118312,4.616739e-02,0.819716,0.324280,0.274510
6,"<think>\n\n</think>\n\n- ""Mentions that the patient was admitted via transfer from another hospital",-0.119521,7.175396e-02,-0.604717,0.158538,0.198880
4,"<think>\n\n</think>\n\n- ""Admitted via physician referral and had a prolonged or complex hospital stay (longer than expected for the admission type)",-0.123414,2.610446e-02,0.218754,0.595434,0.350140
46,"<think>\n\n</think>\n\n- ""The patient is male and belongs to a demographic group with elevated risks for hypertension and cardiovascular disease, as explicitly mentioned in the text.",-0.126869,2.061093e-02,-0.520890,0.077420,0.369748
11,"<think>\n\n</think>\n\n- ""Mentions blood pressure readings that indicate prehypertension or stage 1 hypertension according to clinical guidelines",-0.129412,2.716509e-02,0.015154,0.985125,0.285714
45,"<think>\n\n</think>\n\n- ""Mentions both systolic and diastolic blood pressure readings, with at least one reading indicating elevated or abnormal values (e.g., prehypertension, hypertension, or unknown readings highlighting gaps in cardiovascular data)",-0.131832,1.563464e-02,-0.381639,0.217828,0.378151
41,"<think>\n\n</think>\n\n- ""Admitted from a skilled nursing facility and has a recorded hospital length of stay",-0.132163,4.611709e-01,0.769371,0.492503,0.022409
2,"<think>\n\n</think>\n\n- ""Lacks documentation of height, weight, systolic and diastolic blood pressure, and BMI",-0.134851,1.463271e-02,-2.183055,0.005567,0.355742
43,"<think>\n\n</think>\n\n- ""mentions systolic blood pressure in the elevated range (≥130 mmHg) or diastolic blood pressure in the elevated range (≥80 mmHg), indicating stage 1 or stage 2",-0.135540,2.026890e-02,-1.193213,0.020995,0.288515
49,"<think>\n\n</think>\n\n- ""Mentions psychiatric care transfers or admissions (e.g., internal transfer to or from psychiatric services, urgent admission linked to psychiatric care)",-0.158824,2.022553e-01,-2.815566,0.049319,0.047619
10,"<think>\n\n</think>\n\n- ""Mentions prolonged hospitalization (typically 3 days or more) following an emergency room admission, often highlighting complex care needs or acute decompensation in the context of limited or no prior medical records.",-0.171189,1.169367e-03,-0.641349,0.047976,0.512605
5,"<think>\n\n</think>\n\n- ""Mentions systolic blood pressure in the normal or elevated range (e.g., 120-160 mmHg) in the context of elderly patients (age 80+), often highlighting concerns",-0.200676,2.077660e-02,1.299349,0.049686,0.103641
29,"<think>\n\n</think>\n\n- ""Mentions patients aged 70 to 79 years with normal BMI and blood pressure readings indicating prehypertension or early cardiovascular risk, often highlighting the need for monitoring or preventive care due to age-related vulnerabilities.",-0.213109,6.378250e-03,-1.175635,0.015322,0.131653
39,"<think>\n\n</think>\n\n- ""Mentions elevated systolic blood pressure (≥130 mmHg) without recording height, leading to an uncalculated or unassessable BMI.",-0.227405,9.581183e-02,0.143234,0.895238,0.039216
25,"<think>\n\n</think>\n\n- ""Mentions isolated systolic hypertension (elevated systolic blood pressure with normal diastolic blood pressure)",-0.245550,1.488337e-03,-1.099020,0.046864,0.134454
0,"<think>\n\n</think>\n\n- ""mentions advanced age (80 years or older) in the patient description",-0.289964,1.562159e-05,-0.216267,0.849675,0.187675
21,"<think>\n\n</think>\n\n- ""Mentions patients aged 80 years or older with documented systolic and/or diastolic blood pressure readings and a known or calculable BMI, often highlighting geriatric risk factors such as frailty, falls, or",-0.291759,2.830865e-05,-1.493701,0.191523,0.170868
3,"<think>\n\n</think>\n\n- ""Mentions an extended length of stay (typically 10 days or more) combined with missing or incomplete anthropometric data such as weight, height, BMI, or blood pressure readings.",-0.342560,3.850099e-06,-0.524999,0.533818,0.145658
47,"<think>\n\n</think>\n\n- ""Mentions a prolonged length of stay (generally 10 days or more) in the context of an emergency room admission",-0.345623,7.376688e-07,-1.596218,0.037052,0.168067
1,"<think>\n\n</think>\n\n- ""Patient is 91 years old or older and admitted via the emergency room",-0.450437,9.061827e-04,-2.172962,0.099937,0.039216

Holdout Set Metrics:
R² Score: 0.299
Significant hypotheses: 1/50 (p < 2.000e-03)

In [18]:
pd.set_option('display.max_colwidth', None)
display(evaluation_df)
pd.reset_option('display.max_colwidth')
print("\nHoldout Set Metrics:")
# print(f"R² Score: {metrics['r2']:.3f}")
print(f"Significant hypotheses: {metrics['Significant'][0]}/{metrics['Significant'][1]} " 
    f"(p < {metrics['Significant'][2]:.3e})")
evaluation_df.to_csv(os.path.join(result_dir, "evaluation.csv"), index=False)
with open(os.path.join(result_dir, "metrics.json"), "w") as f:
    json.dump(metrics, f, indent=4)

,hypothesis,separation_score,separation_pval,regression_coef,regression_pval,feature_prevalence
12,"<think>\n\n</think>\n\n- ""mentions internal transfer to or from a psychiatric unit",0.334758,1.044825e-01,3.065696,NaN,0.016807
33,"<think>\n\n</think>\n\n- ""Mentions internal transfer to or from a psychiatric unit in the context of urgent admission",0.334758,1.044825e-01,3.065696,NaN,0.016807
17,"<think>\n\n</think>\n\n- ""The text mentions the patient is a young adult (18–21 years old) with limited or no prior medical records and missing baseline vital signs such as blood pressure, BMI, height, and weight.",0.237720,3.078827e-02,0.989568,0.297442,0.061625
13,"<think>\n\n</think>\n\n- ""The text mentions that the patient's admission type is 'urgent' and was facilitated through a physician referral, with a brief hospital stay (typically 2–3 days) and an absence or minimal presence of prior medical records",0.167584,5.193572e-03,0.392470,0.368766,0.263305
14,"<think>\n\n</think>\n\n- ""The text indicates that this is the patient’s first documented healthcare encounter, as evidenced by the explicit mention of 'no prior medical records,' 'first documented interaction,' or 'initial documented engagement' with the healthcare system.",0.165348,1.719629e-03,1.181885,0.000993,0.495798
15,"<think>\n\n</think>\n\n- ""mentions a patient age between 18 and 22 years old",0.163842,5.732042e-01,0.921543,0.678133,0.008403
32,"<think>\n\n</think>\n\n- ""The text mentions a normal BMI (18.5–24.9) and blood pressure within the optimal or normal range, and indicates that this is the patient's first recorded healthcare encounter (zero prior medical records",0.148887,5.305619e-02,0.286397,0.580962,0.137255
37,"<think>\n\n</think>\n\n- ""Mentions a patient age between 40 and 60 years old",0.146965,1.255471e-02,0.017916,0.963187,0.280112
7,"<think>\n\n</think>\n\n- ""The text includes recorded systolic and diastolic blood pressure values that fall within the normal or borderline elevated range (≤129 mmHg systolic and ≤84 mmHg diastolic), without",0.145628,9.543630e-03,0.044932,0.926766,0.330532
19,"<think>\n\n</think>\n\n- ""The text describes a young adult (age 18-24) with no prior medical records and missing vital signs such as blood pressure, BMI, height, and weight, admitted urgently or emergently for a short",0.144315,2.910959e-01,-0.668369,0.535853,0.039216
27,"<think>\n\n</think>\n\n- ""mentions 'number_of_records: 0' or 'no prior healthcare records'",0.094962,1.426321e-01,0.078352,0.849265,0.212885
35,"<think>\n\n</think>\n\n- ""The text includes the phrase 'admitted urgently via physician referral' or 'admitted via the emergency room under urgent conditions' and mentions a 3-day (or similar short-term) hospital stay, while also stating that",0.083521,1.714674e-01,-0.393914,0.342678,0.252101
22,"<think>\n\n</think>\n\n- ""Mentions a recent emergency room admission or emergency admission type with a hospital stay, coupled with specific BMI categories (overweight, obese, or underweight) and limited prior medical records, suggesting a pattern of reactive healthcare utilization",0.041619,4.367366e-01,0.006339,0.985161,0.563025
26,"<think>\n\n</think>\n\n- ""Mentions blood pressure readings with diastolic values at or below 60 mmHg",0.036585,6.604249e-01,0.516687,0.426243,0.114846
38,"<think>\n\n</think>\n\n- ""Mentions hypotension with specific systolic and diastolic blood pressure readings below normal thresholds (systolic < 120 mmHg and diastolic < 60 mmHg), particularly",0.026471,8.318819e-01,-0.079238,0.922472,0.047619
9,"<think>\n\n</think>\n\n- ""The patient is between 60 and 69 years old.",0.013919,8.406557e-01,-0.482882,0.220250,0.179272
36,"<think>\n\n</think>\n\n- ""mentions 'divorced' marital status and lacks documented systolic and diastolic blood pressure values",-0.004451,9.692525e-01,0.650307,0.263268,0.056022
30,"<think>\n\n</think>\n\n- ""The text mentions that systolic and diastolic blood pressure, BMI, height, and weight are unrecorded or missing, leading to a lack of baseline health metrics.",-0.006173,9.136981e-01,2.483109,0.033913,0.319328
24,"<think>\n\n</think>\n\n- ""The text mentions the absence of recorded systolic and diastolic blood pressure, BMI, height, or weight data, indicating incomplete baseline health metrics.",-0.024553,6.520580e-01,1.086199,0.227524,0.389356
40,"<think>\n\n</think>\n\n- ""Absence of documented systolic and diastolic blood pressure readings",-0.030260,5.744531e-01,-1.118633,0.171448,0.414566
18,"<think>\n\n</think>\n\n- ""Admission was facilitated by a physician referral",-0.032575,5.730226e-01,-0.835962,0.049412,0.302521
34,"<think>\n\n</think>\n\n- ""The text lacks recorded values for weight, height, systolic blood pressure, diastolic blood pressure, and body mass index (BMI), resulting in an absence of baseline biometric and cardiovascular health data.",-0.039364,4.969164e-01,1.051919,0.208921,0.299720
23,"<think>\n\n</think>\n\n- ""Lacks documented values for systolic and diastolic blood pressure, BMI, height, and weight",-0.044252,4.328999e-01,-1.454755,0.142231,0.330532
8,"<think>\n\n</think>\n\n- ""Mentions both systolic and diastolic blood pressure values with specific numerical readings",-0.054747,3.192811e-01,0.055806,0.907622,0.369748
42,"<think>\n\n</think>\n\n- ""Mentions missing or incomplete documentation of systolic and diastolic blood pressure, BMI, height, and weight, indicating a lack of recorded baseline health metrics",-0.058563,2.720792e-01,0.573755,0.482637,0.450980
31,"<think>\n\n</think>\n\n- ""The text does not contain recorded values for height, weight, blood pressure, or BMI.",-0.066667,2.522254e-01,-0.112083,0.925705,0.294118
48,"<think>\n\n</think>\n\n- ""The text mentions the absence or unrecorded status of BMI, systolic and diastolic blood pressure, height, and weight, highlighting significant gaps in baseline clinical metrics that hinder a comprehensive health assessment.",-0.072401,2.099221e-01,-0.847005,0.481546,0.302521
16,"<think>\n\n</think>\n\n- ""Mentions the absence of recorded blood pressure, BMI, weight, and height, indicating gaps in vital sign and anthropometric data.",-0.079626,1.498335e-01,-0.531485,0.572769,0.358543
44,"<think>\n\n</think>\n\n- ""Mentions both systolic and diastolic blood pressure values in the same sentence, often highlighting their clinical significance or relationship to health conditions.",-0.082563,1.261476e-01,0.116303,0.785656,0.406162
20,"<think>\n\n</think>\n\n- ""Mentions that key clinical metrics such as weight, height, blood pressure, and BMI are unknown or unrecorded, which limits a comprehensive assessment of the patient's health status.",-0.085017,1.221899e-01,-0.565943,0.572254,0.366947
28,"<think>\n\n</think>\n\n- ""Mentions systolic blood pressure in the Stage 1 hypertension range (≥130 and <140 mmHg) or diastolic blood pressure in the Stage 1 hypertension range (≥80",-0.118312,4.616739e-02,0.819716,0.324280,0.274510
6,"<think>\n\n</think>\n\n- ""Mentions that the patient was admitted via transfer from another hospital",-0.119521,7.175396e-02,-0.604717,0.158538,0.198880
4,"<think>\n\n</think>\n\n- ""Admitted via physician referral and had a prolonged or complex hospital stay (longer than expected for the admission type)",-0.123414,2.610446e-02,0.218754,0.595434,0.350140
46,"<think>\n\n</think>\n\n- ""The patient is male and belongs to a demographic group with elevated risks for hypertension and cardiovascular disease, as explicitly mentioned in the text.",-0.126869,2.061093e-02,-0.520890,0.077420,0.369748
11,"<think>\n\n</think>\n\n- ""Mentions blood pressure readings that indicate prehypertension or stage 1 hypertension according to clinical guidelines",-0.129412,2.716509e-02,0.015154,0.985125,0.285714
45,"<think>\n\n</think>\n\n- ""Mentions both systolic and diastolic blood pressure readings, with at least one reading indicating elevated or abnormal values (e.g., prehypertension, hypertension, or unknown readings highlighting gaps in cardiovascular data)",-0.131832,1.563464e-02,-0.381639,0.217828,0.378151
41,"<think>\n\n</think>\n\n- ""Admitted from a skilled nursing facility and has a recorded hospital length of stay",-0.132163,4.611709e-01,0.769371,0.492503,0.022409
2,"<think>\n\n</think>\n\n- ""Lacks documentation of height, weight, systolic and diastolic blood pressure, and BMI",-0.134851,1.463271e-02,-2.183055,0.005567,0.355742
43,"<think>\n\n</think>\n\n- ""mentions systolic blood pressure in the elevated range (≥130 mmHg) or diastolic blood pressure in the elevated range (≥80 mmHg), indicating stage 1 or stage 2",-0.135540,2.026890e-02,-1.193213,0.020995,0.288515
49,"<think>\n\n</think>\n\n- ""Mentions psychiatric care transfers or admissions (e.g., internal transfer to or from psychiatric services, urgent admission linked to psychiatric care)",-0.158824,2.022553e-01,-2.815566,0.049319,0.047619
10,"<think>\n\n</think>\n\n- ""Mentions prolonged hospitalization (typically 3 days or more) following an emergency room admission, often highlighting complex care needs or acute decompensation in the context of limited or no prior medical records.",-0.171189,1.169367e-03,-0.641349,0.047976,0.512605
5,"<think>\n\n</think>\n\n- ""Mentions systolic blood pressure in the normal or elevated range (e.g., 120-160 mmHg) in the context of elderly patients (age 80+), often highlighting concerns",-0.200676,2.077660e-02,1.299349,0.049686,0.103641
29,"<think>\n\n</think>\n\n- ""Mentions patients aged 70 to 79 years with normal BMI and blood pressure readings indicating prehypertension or early cardiovascular risk, often highlighting the need for monitoring or preventive care due to age-related vulnerabilities.",-0.213109,6.378250e-03,-1.175635,0.015322,0.131653
39,"<think>\n\n</think>\n\n- ""Mentions elevated systolic blood pressure (≥130 mmHg) without recording height, leading to an uncalculated or unassessable BMI.",-0.227405,9.581183e-02,0.143234,0.895238,0.039216
25,"<think>\n\n</think>\n\n- ""Mentions isolated systolic hypertension (elevated systolic blood pressure with normal diastolic blood pressure)",-0.245550,1.488337e-03,-1.099020,0.046864,0.134454
0,"<think>\n\n</think>\n\n- ""mentions advanced age (80 years or older) in the patient description",-0.289964,1.562159e-05,-0.216267,0.849675,0.187675
21,"<think>\n\n</think>\n\n- ""Mentions patients aged 80 years or older with documented systolic and/or diastolic blood pressure readings and a known or calculable BMI, often highlighting geriatric risk factors such as frailty, falls, or",-0.291759,2.830865e-05,-1.493701,0.191523,0.170868
3,"<think>\n\n</think>\n\n- ""Mentions an extended length of stay (typically 10 days or more) combined with missing or incomplete anthropometric data such as weight, height, BMI, or blood pressure readings.",-0.342560,3.850099e-06,-0.524999,0.533818,0.145658
47,"<think>\n\n</think>\n\n- ""Mentions a prolonged length of stay (generally 10 days or more) in the context of an emergency room admission",-0.345623,7.376688e-07,-1.596218,0.037052,0.168067
1,"<think>\n\n</think>\n\n- ""Patient is 91 years old or older and admitted via the emergency room",-0.450437,9.061827e-04,-2.172962,0.099937,0.039216

Holdout Set Metrics:
Significant hypotheses: 1/50 (p < 2.000e-03)

In [19]:
evaluation_df
with open(os.path.join(result_dir, 'hypotheses_info.jsonl'), "w") as f:
    for _, row in evaluation_df.iterrows():
        f.write(json.dumps(row.to_dict()) + "\n")