In [1]:
# HypotheSAEs Quickstart
# This notebook demonstrates basic usage of HypotheSAEs on a sample of the Yelp review dataset
import os

%load_ext autoreload
%autoreload 2

import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'  # Set to '0' to use the first GPU, or 'cpu' to run on CPU
os.environ['OPENAI_KEY_SAE'] = 'EMPTY' # Replace with your OpenAI API key, or with another environment variable (e.g. os.environ['OPENAI_API_
import numpy as np
import pandas as pd

from hypothesaes.quickstart import train_sae, interpret_sae, generate_hypotheses, evaluate_hypotheses
from hypothesaes.embedding import get_openai_embeddings, get_local_embeddings

/home/sevan/anaconda3/envs/llm/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

**Load data**

The dataset we're using here is a subset of 20K Yelp reviews, with 2K reviews used for validation (during SAE training). 

The target variable is the `stars` column, which is a rating between 1 and 5. We treat this as a regression task.

There are also 2K reviews used for holdout evaluation, which we'll use at the end of the notebook.

In [2]:
CACHE_SIGNAL = "concurrent"

In [22]:
current_dir = os.getcwd()
if current_dir.endswith("notebooks"):
    prefix = "../"
else:
    prefix = "./"
val_ratio = 0.1  # Ratio of training data to use for validation
import sklearn
import sklearn.model_selection
few_shot_examples = 5
# base_dir = os.path.join(prefix, "demo-data")
# train_df = pd.read_json(os.path.join(base_dir, "yelp-demo-train-20K.json"), lines=True)
# val_df = pd.read_json(os.path.join(base_dir, "yelp-demo-val-2K.json"), lines=True)

# texts = train_df['text'].tolist()
# labels = train_df['stars'].values
# val_texts = val_df['text'].tolist() # These are only used for early stopping of SAE training, so we don't need labels.
from utils import df_to_prompts
import json
import re
base_dir = os.path.join(prefix, 'data_processed')
train_X = pd.read_csv(os.path.join(base_dir, "X_train.csv"))
train_y = pd.read_csv(os.path.join(base_dir, "y_train.csv")).values.ravel()
test_X = pd.read_csv(os.path.join(base_dir, "X_test.csv"))
test_y = pd.read_csv(os.path.join(base_dir, "y_test.csv")).values.ravel()
label_type = set(train_y).union(set(test_y))
# number_dict = {label: i for i, label in enumerate(label_type)}
number_dict = {label: 1 if label == 'Home' else 0 for label in label_type}
label_train = [number_dict[label] for label in train_y]
label_test = [number_dict[label] for label in test_y]
# train_texts = df_to_prompts(few_shot_row, few_shot_label, train_X.iloc[few_shot_examples:, :], few_shot_examples=few_shot_examples)
pattern = re.compile(r"<think>.*?</think>", re.DOTALL)  # 匹配 <think> 到 </think>，包括换行
train_texts_idx_profile = []
test_texts_idx_profile = []
train_jsonl = os.path.join(base_dir, f"train_profile_{CACHE_SIGNAL}.jsonl")
test_josnl = os.path.join(base_dir, f"test_profile_{CACHE_SIGNAL}.jsonl")
if len(CACHE_SIGNAL) == 0 or 'toy' in CACHE_SIGNAL :
    train_jsonl = os.path.join(base_dir, "train_profile_toy.jsonl")
    test_josnl = os.path.join(base_dir, "test_profile_toy.jsonl")
with open(train_jsonl) as f:
    for line in f:
        obj = json.loads(line)
        profile = obj["profile"]
        profile = re.sub(pattern, "", profile)  # 删除 <think>...</think>
        obj["profile"] = profile.strip()
        train_texts_idx_profile.append((obj['profile'], obj['idx']))
    sorted_train_texts_idx_profile = sorted(train_texts_idx_profile, key=lambda x: x[1])
train_texts = [item[0] for item in sorted_train_texts_idx_profile]
with open(test_josnl)as f:
    for line in f:
        obj = json.loads(line)
        profile = obj["profile"]
        profile = re.sub(pattern, "", profile)  # 删除 <think>...</think>
        obj["profile"] = profile.strip()
        test_texts_idx_profile.append((obj['profile'], obj['idx']))
    sorted_test_texts_idx_profile = sorted(test_texts_idx_profile, key=lambda x: x[1])
test_texts = [item[0] for item in sorted_test_texts_idx_profile]
print(set(train_y), set(test_y))    
number_dict

{'Home with Services', 'Home', 'Deceased / Hospice', 'Facility-Based Care'} {'Home', 'Facility-Based Care', 'Deceased / Hospice', 'Home with Services'}

{'Deceased / Hospice': 0,
 'Home': 1,
 'Facility-Based Care': 0,
 'Home with Services': 0}

In [23]:
#count label distribution
train_label_distribution = pd.Series(train_y).value_counts()
test_label_distribution = pd.Series(test_y).value_counts()
train_label_distribution,  test_label_distribution

(Home                   3046
 Facility-Based Care    1266
 Home with Services     1198
 Deceased / Hospice      543
 Name: count, dtype: int64,
 Home                   553
 Home with Services     212
 Facility-Based Care    199
 Deceased / Hospice     104
 Name: count, dtype: int64)

In [24]:
texts, val_texts, labels, val_labels = sklearn.model_selection.train_test_split(
    train_texts, label_train, test_size=val_ratio, random_state=42, shuffle=True
)

In [25]:
len(test_y)

1068

**Compute text embeddings for your dataset**

We'll compute text embeddings for a training set, and optionally a validation set. The validation embeddings are used for SAE eval and early-stopping during training.

Embeddings will be stored in the `emb_cache` directory (or `os.environ["EMB_CACHE_DIR"]` if you set it) using the `cache_name` parameter, so you only need to compute embeddings once.

You can use OpenAI or a local model.

Local models will run much faster on GPU. The default local model is `nomic-ai/modernbert-embed-base`. You can use any sentence-transformers model, but please read the model's docs; you may need to edit `get_local_embeddings`.

In [26]:
EMBEDDER = "Qwen/Qwen3-Embedding-0.6B" # OpenAI
# EMBEDDER = "nomic-ai/modernbert-embed-base" # Huggingface model, will run locally
CACHE_NAME = f"yelp_quickstart_{EMBEDDER}"

# text2embedding = get_openai_embeddings(texts + val_texts, model=EMBEDDER, cache_name=CACHE_NAME)
text2embedding = get_local_embeddings(texts + val_texts, model=EMBEDDER, batch_size=32, cache_name=CACHE_NAME)
embeddings = np.stack([text2embedding[text] for text in texts])

train_embeddings = np.stack([text2embedding[text] for text in texts])
val_embeddings = np.stack([text2embedding[text] for text in val_texts])
text2embedding_test = get_local_embeddings(test_texts, model=EMBEDDER, batch_size=8, cache_name=CACHE_NAME)
test_embeddings = np.stack([text2embedding_test[text] for text in test_texts])

Loading embedding chunks:   0%|          | 0/8 [00:00<?, ?it/s]

Loading embedding chunks: 100%|██████████| 8/8 [00:00<00:00, 47.48it/s]

Loaded 13614 embeddings in 0.2s

Loading embedding chunks: 100%|██████████| 8/8 [00:00<00:00, 55.41it/s]

Loaded 13614 embeddings in 0.1s

**Train SAE(s)** 

Using different values of $M$ and $k$ will produce features at different levels of granularity. You can train multiple SAEs if you'd like to produce features at varying granularity, but this is optional.

See the README for more details about selecting $M$ and $k$.

In [27]:
checkpoint_dir = os.path.join(prefix, f"checkpoints_{CACHE_SIGNAL}", CACHE_NAME)
# sae_256_8 = train_sae(embeddings=train_embeddings, M=256, K=8, checkpoint_dir=checkpoint_dir, val_embeddings=val_embeddings, n_epochs=1000, patience=100)
# sae_32_4 = train_sae(embeddings=train_embeddings, M=32, K=4, checkpoint_dir=checkpoint_dir, val_embeddings=val_embeddings, n_epochs=1000, patience=100)
# sae_512_8 = train_sae(embeddings=train_embeddings, M=512, K=8, checkpoint_dir=checkpoint_dir, val_embeddings=val_embeddings, n_epochs=1000, patience=100)
sae_128_64 = train_sae(embeddings=train_embeddings, M=128, K=8, checkpoint_dir=checkpoint_dir, val_embeddings=val_embeddings, n_epochs=1000, patience=100)
sae_128_16 = train_sae(embeddings=train_embeddings, M=128, K=16, checkpoint_dir=checkpoint_dir, val_embeddings=val_embeddings, n_epochs=1000, patience=100)
sae_256_16 = train_sae(embeddings=train_embeddings, M=256, K=16, checkpoint_dir=checkpoint_dir, val_embeddings=val_embeddings, n_epochs=1000, patience=100)
sae_128_32 = train_sae(embeddings=train_embeddings, M=128, K=32, checkpoint_dir=checkpoint_dir, val_embeddings=val_embeddings, n_epochs=1000, patience=100)
sae_256_32 = train_sae(embeddings=train_embeddings, M=256, K=32, checkpoint_dir=checkpoint_dir, val_embeddings=val_embeddings, n_epochs=1000, patience=100)
sae_512_32 = train_sae(embeddings=train_embeddings, M=512, K=32, checkpoint_dir=checkpoint_dir, val_embeddings=val_embeddings, n_epochs=1000, patience=100)
sae_128_64 = train_sae(embeddings=train_embeddings, M=128, K=64, checkpoint_dir=checkpoint_dir, val_embeddings=val_embeddings, n_epochs=1000, patience=100)
sae_256_64 = train_sae(embeddings=train_embeddings, M=256, K=64, checkpoint_dir=checkpoint_dir, val_embeddings=val_embeddings, n_epochs=1000, patience=100)
sae_list = [sae_128_32, sae_128_64, sae_256_64]

Loaded model from ./checkpoints_concurrent/yelp_quickstart_Qwen/Qwen3-Embedding-0.6B/SAE_M=128_K=8.pt onto device cuda
Loaded model from ./checkpoints_concurrent/yelp_quickstart_Qwen/Qwen3-Embedding-0.6B/SAE_M=128_K=16.pt onto device cuda
Loaded model from ./checkpoints_concurrent/yelp_quickstart_Qwen/Qwen3-Embedding-0.6B/SAE_M=256_K=16.pt onto device cuda
Loaded model from ./checkpoints_concurrent/yelp_quickstart_Qwen/Qwen3-Embedding-0.6B/SAE_M=128_K=32.pt onto device cuda
Loaded model from ./checkpoints_concurrent/yelp_quickstart_Qwen/Qwen3-Embedding-0.6B/SAE_M=256_K=32.pt onto device cuda
Loaded model from ./checkpoints_concurrent/yelp_quickstart_Qwen/Qwen3-Embedding-0.6B/SAE_M=512_K=32.pt onto device cuda
Loaded model from ./checkpoints_concurrent/yelp_quickstart_Qwen/Qwen3-Embedding-0.6B/SAE_M=128_K=64.pt onto device cuda
Loaded model from ./checkpoints_concurrent/yelp_quickstart_Qwen/Qwen3-Embedding-0.6B/SAE_M=256_K=64.pt onto device cuda

**Interpret neurons**  

Interpret a random subset of neurons in the SAE to sanity-check that the learned features, and their interpretations, seem reasonable. We generate and print labels for `n_random_neurons` neurons, and we also print out the top-activating texts for each neuron.

In [ ]:
# This instruction will be included in the neuron interpretation prompt.
# The below instructions are specific to Yelp, but you can customize this for your task.
# If you don't pass in task-specific instructions, there is a generic instruction (see src/interpret_neurons.py);
# task-specific instructions are optional, but they help produce hypotheses at the desired level of specificity.

TASK_SPECIFIC_INSTRUCTIONS = """You are a medical assistant. You need add hypothesis for each neuron, which should describe a specific aspect of the text.
Features should describe a specific aspect of patient profile. For example:
- "mentions patient has a tumor in the left lung"
- "indicates patient is allergic to penicillin"
""" 
# """All of the texts are reviews of restaurants on Yelp.
# Features should describe a specific aspect of the review. For example:
# - "mentions long wait times to receive service"
# - "praises how a dish was cooked, with phrases like 'perfect medium-rare'\""""
# Interpret random neurons
results = interpret_sae(
    texts=texts,
    embeddings=train_embeddings,
    sae=sae_list,
    n_random_neurons=30,
    print_examples_n=10,
    task_specific_instructions=TASK_SPECIFIC_INSTRUCTIONS,
    interpreter_model="Qwen/Qwen3-32B",
    annotator_model="Qwen/Qwen3-32B",  # Use the same model for both interpretation and annotation
    max_interpretation_tokens= 1024,
)

Computing activations (batchsize=16384): 100%|██████████| 1/1 [00:00<00:00, 188.64it/s]
Computing activations (batchsize=16384): 100%|██████████| 1/1 [00:00<00:00, 186.75it/s]
Computing activations (batchsize=16384): 100%|██████████| 1/1 [00:00<00:00, 185.63it/s]

Activations shape: (5447, 512)

Generating 1 interpretation(s) per neuron: 100%|██████████| 30/30 [00:09<00:00,  3.12it/s]

Neuron 485 (from SAE M=256, K=64): <think>

</think>

- "Mentions stage 1 hypertension with a systolic blood pressure reading ≥130 mmHg and/or diastolic ≥90 mmHg, specifically without indicating higher stages of hypertension or missing blood pressure data.

Top activating examples:
1. The patient is a 44-year-old male presenting with a normal body mass index (BMI) of 24.6, calculated from a height of 71 inches (5'11") and weight of 176.37 lbs, indicating a healthy weight distribution for his stature. His blood pressure reading of 130/73 mmHg falls within the prehypertensive range for systolic pressure, necessitating cautious monitoring to prevent progression to hypertension, particularly given his age and lack of prior medical records suggesting established cardiovascular management. Admitted urgently from an external hospital transfer, his three-day length of stay underscores the acute nature of his current condition, though the absence of historical health records complicates the assessment of chronic risks or prior interventions. As a single individual identifying under the "other" category for both race and insurance type, potential social determinants of health—such as access to preventive care or health literacy in English—may influence his long-term outcomes. While his BMI and diast[... rest of text is truncated]
2. This 55-year-old Asian Chinese woman presents a generally favorable health profile, marked by a normal BMI of 23.2, calculated from a height of 60 inches (5 feet) and a weight of 119 pounds, indicating a healthy weight distribution for her stature. However, her blood pressure reading of 140/82 mmHg reveals stage 1 hypertension, as per clinical guidelines, with elevated systolic pressure posing a moderate cardiovascular risk despite a diastolic value within the normal range. Her recent healthcare utilization highlights an emergency room admission categorized as an "ew emer." (urgent/emergent), with a 3-day hospital stay, suggesting an acute or severe presentation necessitating immediate inpatient care. The limited number of medical records (n=2) may reflect either a newly identified health issue or infrequent engagement with non-urgent care settings, potentially influenced by her "other" insurance status, which could impact access to preventive services. As a married individual, she may benefit from spousal su[... rest of text is truncated]
3. The 34-year-old female patient presents with a normal body mass index (BMI) of 22.2, reflecting a healthy weight distribution for her height of 67 inches (5'7") and weight of 142 lbs. Her blood pressure reading of 130/80 mmHg indicates prehypertension, warranting cautious monitoring due to the elevated systolic value, though diastolic pressure remains within the normal range. Admitted urgently via physician referral, her six-day hospital stay suggests a clinically significant acute episode, though her lack of prior medical records implies either new engagement with the healthcare system or potential gaps in continuity of care. As a single, English-speaking individual identifying under the "other" category for both race and insurance type, her profile highlights the need to consider socioeconomic and cultural factors that may influence health literacy or access to preventive services. While her current BMI and absence of chronic conditions suggest low immediate risk, the prehypertensive reading and urgent admi[... rest of text is truncated]
4. The 60-year-old white male patient presents with a BMI of 26.2, categorizing him as overweight, which places him at elevated risk for metabolic and cardiovascular complications despite currently normal blood pressure readings of 102/64 mmHg. His systolic blood pressure, while within the normal range, leans toward the lower end of healthy parameters, though this may reflect individual variability or transient factors unrelated to chronic disease. The patient’s recent healthcare utilization reveals a single admission via walk-in/self-referral for an observation admit, with a brief length of stay (3 days), suggesting either a nonurgent presentation or a need for short-term monitoring without immediate inpatient intervention. As a single, English-speaking individual with privately held insurance (coded as “other”), his social determinants highlight potential reliance on self-managed health decisions, though limited data on socioeconomic factors or support systems preclude deeper analysis. The absence of prior rec[... rest of text is truncated]
5. The 47-year-old African American woman presents with a normal BMI of 23.6, calculated from her height of 65 inches and weight of 148.25 pounds, indicating a healthy weight distribution for her stature. However, her blood pressure reading of 142/92 mmHg places her in stage 1 hypertension, a critical finding that warrants closer monitoring given her race and age, both recognized risk factors for hypertension-related complications such as cardiovascular disease. Admitted via physician referral for a surgical same-day procedure, her two-day hospital stay suggests either postoperative observation needs or uncomplicated recovery, though the absence of prior medical records highlights a potential gap in longitudinal care coordination. As a married, English-speaking patient with "other" insurance, her healthcare navigation may benefit from structured follow-up to ensure continuity, particularly for managing her elevated blood pressure. While her current BMI status is reassuring, her cardiovascular risk profile merits[... rest of text is truncated]
6. The patient is a 50-year-old male presenting with a normal body mass index (BMI) of 21.0, calculated from a height of 67 inches and weight of 134 pounds, yet his blood pressure reading of 153/86 mmHg indicates stage 1 hypertension, signaling a critical cardiovascular risk factor requiring further evaluation. Admitted through the emergency room under an unspecified insurance category, his 16-day length of stay suggests a complex or unresolved acute health event, though the absence of prior medical records complicates the assessment of chronic conditions or historical comorbidities. As a single, English-speaking individual with unknown racial heritage, social determinants such as support systems and health literacy may influence his care trajectory, particularly given the lack of documented prior healthcare engagement. While his BMI falls within the healthy range, the elevated systolic blood pressure underscores the need for targeted interventions, including dietary sodium reduction, regular physical activity, [... rest of text is truncated]
7. The patient is a 78-year-old white male presenting with a normal body mass index (BMI) of 24.2, indicating a healthy weight for his height of 69.6 inches (5 feet 9.5 inches) and weight of 172 pounds. His blood pressure reading of 142 mmHg systolic and 82 mmHg diastolic highlights an elevated risk for hypertension, particularly given his advanced age, as systolic readings consistently above 140 mmHg are associated with increased cardiovascular strain. This finding, coupled with his recent surgical same-day admission for a procedure facilitated through physician referral, suggests a healthcare utilization pattern centered on acute, specialized care rather than ongoing outpatient management. The admission resulted in a four-day hospital stay, slightly exceeding the typical duration for same-day surgical interventions, which may reflect postoperative monitoring needs or recovery complexities in an elderly population. Demographically, the patient’s divorced marital status and English language preference underscore[... rest of text is truncated]
8. The 60-year-old male patient presents with a BMI of 26.3, categorizing him as overweight, and a blood pressure reading of 164/95 mmHg, indicative of stage 1 hypertension, both of which elevate his cardiovascular risk profile. Admitted via physician referral for a surgical same-day procedure, this marks his first documented healthcare encounter in the system, as evidenced by the absence of prior records. His demographic factors—including race (White), marital status (married), and English language preference—suggest a socially stable background, though the "other" insurance designation warrants further clarification to optimize care coordination. The combination of hypertension and overweight status necessitates immediate attention to modifiable risk factors, such as dietary sodium intake, physical inactivity, and weight management, to mitigate progression to more severe cardiovascular complications. Given his age and current health status, targeted interventions—such as a tailored exercise regimen, nutritiona[... rest of text is truncated]
9. The 51-year-old white female patient presents with a normal body mass index (BMI) of 22.9, indicating a healthy weight distribution relative to her height of 64 inches (5′4″) and weight of 133.2 lbs. However, her blood pressure reading of 153/94 mmHg places her in Stage 1 hypertension per clinical guidelines, signaling an elevated cardiovascular risk that warrants close monitoring. Admitted emergently to the emergency room with an uncomplicated diagnosis, her 13-day inpatient stay suggests either a complex acute condition or prolonged observation for instability, though her lack of prior medical records implies this may be her first significant healthcare engagement in recent years. As a widowed individual with insurance categorized as “other”—potentially indicating a non-traditional or underinsured status—she may face barriers to routine preventive care, compounding risks for undiagnosed comorbidities. While her BMI falls within the “normal” range, her hypertension highlights the need for dietary sodium redu[... rest of text is truncated]
10. This 44-year-old white female patient presents with a body mass index (BMI) of 33.4, categorizing her as obese, which places her at increased risk for comorbidities such as cardiovascular disease, type 2 diabetes, and musculoskeletal disorders. Her blood pressure reading of 138/74 mmHg indicates elevated systolic pressure, nearing the threshold for hypertension (≥140 mmHg), though her diastolic value remains within the normal range. As a married individual with English as her primary language, her social support network may offer resources for lifestyle interventions, though her "other" insurance classification could pose barriers to consistent preventive care. During this hospitalization, she was admitted through the emergency room via an emergency admit type, with a length of stay spanning 12 days—a duration suggesting either complex clinical management or potential delays in care coordination. Nine medical records associated with this visit highlight either multifaceted treatment episodes or recurring heal[... rest of text is truncated]
----------------------------------------------------------------------------------------------------

Neuron 28 (from SAE M=128, K=32): <think>

</think>

- "Mentions a body mass index (BMI) that classifies the patient as overweight or obese (≥ 25)

Top activating examples:
1. This 63-year-old White female presents with a normal BMI of 20.6, calculated from a weight of 107 pounds and a height of 60.5 inches, reflecting a healthy weight distribution for her stature. Her current blood pressure of 110/66 mmHg falls within the optimal range, suggesting良好的 cardiovascular status at this time. However, her admission to the emergency room via the emergency department underscores an acute health event requiring three days of inpatient care, though the underlying cause remains unspecified in the provided data. Analysis of her healthcare utilization reveals five prior medical records, indicating moderate engagement with the healthcare system, though the frequency and nature of these encounters warrant further investigation to identify recurring conditions or preventive care gaps. While her demographic profile—married, English-speaking, and insured through Medicare—suggests stable social determinants of health, her age and gender place her at increased risk for conditions such as osteoporosis [... rest of text is truncated]
2. This 63-year-old married female presents with a normal body mass index (BMI) of 24.7, indicating a healthy weight distribution relative to her height of 66.5 inches and weight of 155.4 pounds. Her blood pressure reading of 142/79 mmHg reveals isolated systolic hypertension, a common precursor to cardiovascular risk in older adults, though her diastolic pressure remains within the normal range. The patient’s recent healthcare utilization includes a surgical same-day admission with a 2-day hospital stay, likely for a procedure necessitating brief inpatient monitoring, as documented across three clinical records. Admitted via physician referral, her care pathway suggests coordinated management by a specialist, though the unspecified nature of her insurance coverage—categorized as “other”—may warrant further clarification to optimize care continuity. While her BMI status mitigates metabolic syndrome concerns, the elevated systolic blood pressure, combined with her age and sex, positions her at moderate risk for c[... rest of text is truncated]
3. The 63-year-old female patient presents with a body mass index (BMI) of 18.9, falling within the normal range, which aligns with her stable weight of 118.2 pounds and height of 66 inches. Her blood pressure readings of 104/60 mmHg indicate hypotension, placing her below the lower limits of the typical normal range (90/60 mmHg), a finding that warrants closer monitoring for symptoms such as dizziness or syncope, particularly in an older adult population. This visit, characterized by an elective admission via physician referral and a brief hospital stay of two days, reflects a planned healthcare engagement rather than an acute crisis, suggesting a proactive approach to managing her health. However, the absence of prior medical records raises questions about the continuity of her care, as there is limited historical data to contextualize her current condition or identify long-term trends. Given her age and gender, potential health risks include osteoporosis, cardiovascular vulnerabilities linked to hypotension, [... rest of text is truncated]
4. This 27-year-old married female presents with a body mass index (BMI) of 30.2, categorizing her as obese, a status that elevates her risk for comorbidities such as cardiovascular disease, type 2 diabetes, and sleep apnea. While her current systolic and diastolic blood pressure readings are unrecorded, her BMI underscores the importance of monitoring for hypertension, a condition frequently associated with obesity. The patient’s recent urgent admission via physician referral, coupled with a brief hospital stay of two days, suggests an acute episode requiring immediate intervention, though the absence of prior medical records in this system indicates either a new patient relationship or potential gaps in longitudinal care. Her demographic profile, including self-identification in the “other” category for both race and insurance type, highlights the need for further clarification on social determinants of health and access barriers, particularly as language preferences remain unspecified—potentially complicating[... rest of text is truncated]
5. The patient is a 29-year-old Hispanic/Latino woman of Dominican origin presenting with a body mass index (BMI) of 39.1, categorizing her as obese according to standard clinical thresholds. Despite her young age, this BMI elevates her risk for obesity-associated comorbidities such as type 2 diabetes, cardiovascular disease, and sleep apnea, warranting close monitoring of metabolic and cardiovascular parameters. Her blood pressure readings of 112/70 mmHg fall within the normal range, suggesting no immediate hypertensive concern; however, the long-term cardiovascular implications of obesity necessitate proactive intervention. The patient was admitted urgently via physician referral, indicating a complex or acute health issue requiring specialized care, though the brief length of stay (3 days) may reflect a targeted treatment approach or resource constraints. As a married individual with English as her primary language, her social context may influence care adherence and communication with providers. The presence[... rest of text is truncated]
6. The patient is a 59-year-old married female admitted for a two-day observation stay following an emergency room evaluation, with a body mass index (BMI) of 43.1, categorizing her as severely obese. While blood pressure measurements are not documented in the provided records, her BMI signals a critical elevation in health risks, including metabolic syndrome, cardiovascular strain, and respiratory compromise, all of which may have contributed to her acute presentation. Her weight of 274.91 pounds (124.7 kg) and height of 5 feet 7 inches (67 inches) underscore the urgency of addressing obesity-related comorbidities, though the absence of systolic and diastolic blood pressure data limits immediate cardiovascular risk stratification. This visit marks her current healthcare engagement, with no prior records indicated in the system, suggesting either a new patient relationship or potential gaps in documented care continuity. As an English-speaking individual with "other" insurance, barriers to preventive care or spe[... rest of text is truncated]
7. The 53-year-old female patient presents with a critical body mass index (BMI) of 57.5, categorizing her as severely obese (class III), which significantly elevates her risk for comorbidities such as cardiovascular disease, type 2 diabetes, and obstructive sleep apnea. Despite her emergency room admission for an unspecified acute condition, no documented systolic or diastolic blood pressure readings were recorded during this encounter, raising concerns about potential undiagnosed hypertension or incomplete initial assessments. As a previously untreated patient with zero prior medical records in the system, her sudden emergency presentation suggests either a lack of ongoing primary care or a severe decompensation of an underlying condition. Her demographic profile—single, English-speaking, and insured under an unspecified “other” category—may reflect socioeconomic or systemic barriers to consistent healthcare access, compounded by her complex health needs. Given her extreme obesity, immediate interventions shou[... rest of text is truncated]
8. The patient is a 57-year-old white male presenting with a body mass index (BMI) of 33.3, categorizing him as obese according to standard clinical thresholds. While his systolic and diastolic blood pressure values remain unrecorded in this dataset, his BMI signals an elevated risk for hypertension and cardiovascular complications, warranting further investigation during his next clinical encounter. Admitted electively via physician referral for a 5-day hospital stay, his healthcare utilization pattern suggests a structured, proactive approach to managing a known medical condition, though the presence of seven clinical records indicates a history of repeated interactions with the healthcare system. His marital status and English-language proficiency may facilitate adherence to post-discharge care instructions, though the "other" designation under insurance type raises questions about potential financial barriers to continuous care. Given his obesity, priority health risks include type 2 diabetes, sleep apnea, a[... rest of text is truncated]

**Generate hypotheses**

Generate hypotheses which are predictive of the target variable.

The `selection_method` parameter defines how we compute neuron predictiveness (see `src/select_neurons.py` for more details):
- "separation_score": E[target | top-activating examples] - E[target | zero-activating examples]
- "correlation": pearson(neuron activations, target variable)
- "lasso": select N nonzero features with an L1 regularized model

This cell outputs a dataframe with the following columns:
- `neuron_idx`: The index of the neuron in the SAE (if you're using multiple SAEs, this will be a global index across all of them).
- `source_sae`: The SAE that the neuron was selected from.
- `target_{selection_method}`: The predictiveness of the neuron for the target variable, using the selected `selection_method`.
- `interpretation`: The natural language interpretation of the neuron.
- `interp_fidelity_score`: The F1 fidelity score for how well the neuron's interpretation actually corresponds to its activation pattern.

In [29]:
RESULT_EXTRA_INFO = "10_Hypotheses"

In [ ]:
selection_method = "lasso"
multi_class = True  # Set to True for direct multi-class classification, False for using one vs. rest classification
if len(set(labels)) == 2:
    selection_method = "lasso"  # Use logistic regression for binary classification
    multi_class = True
result_dir = f'result_cache/{CACHE_SIGNAL}_one_vs_rest_{RESULT_EXTRA_INFO}' if not multi_class else f'result_cache/{CACHE_SIGNAL}_multi_class_{RESULT_EXTRA_INFO}'

if not os.path.exists(result_dir):
    os.makedirs(result_dir)
if multi_class:
    results = generate_hypotheses(
        texts=texts,
        labels=labels,
        embeddings=embeddings,
        sae=sae_list,
        cache_name=CACHE_NAME,
        selection_method=selection_method,
        n_selected_neurons=20,
        n_candidate_interpretations=20,
        task_specific_instructions=TASK_SPECIFIC_INSTRUCTIONS,
        classification=True,
        interpreter_model="Qwen/Qwen3-32B",
        annotator_model="Qwen/Qwen3-32B",  # Use the same model for both interpretation and annotation
    )

    print("\nMost predictive features of Yelp reviews:")
    pd.set_option('display.max_colwidth', None)
    display(results.sort_values(by=f"target_{selection_method}", ascending=False))
    pd.reset_option('display.max_colwidth')
    results.to_csv(os.path.join(result_dir, f"hypotheses_{selection_method}.csv"), index=False)
else:
    results = {}
    for key in number_dict.keys():
        converted_key = {number_dict[dic_key]: 1 if dic_key == key else 0 for dic_key in number_dict.keys()}
        converted_label = [converted_key[label] for label in labels]
        print(len(converted_label))
        results[f'{key}_vs_rest'] = generate_hypotheses(
            texts=texts,
            labels=converted_label,
            embeddings=embeddings,
            sae=sae_list,
            cache_name=CACHE_NAME,
            selection_method=selection_method,
            n_selected_neurons=15,
            n_candidate_interpretations=3,
            task_specific_instructions=TASK_SPECIFIC_INSTRUCTIONS,
            classification=True,
            n_scoring_examples= 1000,  # Number of examples to use for scoring hypotheses
            interpreter_model="Qwen/Qwen3-32B",
            annotator_model="Qwen/Qwen3-32B",  # Use the same model for both interpretation and annotation
        )
    for key, value in results.items():
        key_norm = key.replace("/", "or")
        key_norm = key_norm.replace(" ", "_")
        print(f"\nMost predictive features of Yelp reviews for {key}:")
        pd.set_option('display.max_colwidth', None)
        display(value.sort_values(by=f"target_{selection_method}", ascending=False))
        pd.reset_option('display.max_colwidth')
        results[key].to_csv(os.path.join(result_dir, f"hypotheses_{key_norm}_{selection_method}.csv"), index=False)

Embeddings shape: (5447, 1024)

Computing activations (batchsize=16384): 100%|██████████| 1/1 [00:00<00:00, 125.38it/s]
Computing activations (batchsize=16384): 100%|██████████| 1/1 [00:00<00:00, 177.43it/s]
Computing activations (batchsize=16384):   0%|          | 0/1 [00:00<?, ?it/s]

Computing activations (batchsize=16384): 100%|██████████| 1/1 [00:00<00:00, 190.05it/s]

Activations shape: (5447, 512)

Step 1: Selecting top 10 predictive neurons
LASSO iteration   L1 Alpha # Features   Time (s)
----------------------------------------

       0   1.00e-01        503      14.51
       1   3.16e+01        148       0.25
       2   5.62e+02          2       0.06
       3   1.33e+02         34       0.10
       4   2.74e+02         12       0.08
       5   3.92e+02          3       0.07
       6   3.28e+02          9       0.10
       7   3.00e+02         10       0.08

Found alpha=3.00e+02 yielding exactly 10 features
Total search time: 15.26s

Step 2: Interpreting selected neurons

Generating 20 interpretation(s) per neuron: 100%|██████████| 200/200 [00:33<00:00,  6.05it/s]

Step 3: Scoring Interpretations
Found 700 cached items; annotating 19300 uncached items

Scoring neuron interpretation fidelity (10 neurons; 20 candidate interps per neuron; 100 examples to score each interp): 100%|██████████| 19300/19300 [13:05<00:00, 24.56it/s]

Most predictive features of Yelp reviews:

,neuron_idx,source_sae,target_lasso,interpretation,f1_fidelity_score
0,197,"(128, 64)",0.614381,"<think>\n\n</think>\n\n- ""The text mentions the patient being admitted through the emergency room or having an emergency/urgent admission, and also emphasizes the patient's advanced age (typically 80 years or older) combined with missing or undocumented vital signs such",0.939574
1,166,"(128, 64)",0.141889,"<think>\n\n</think>\n\n- ""Lacks documentation of height, weight, systolic and diastolic blood pressure, and BMI",0.768608
2,457,"(256, 64)",0.047629,"<think>\n\n</think>\n\n- ""Mentions an extended length of hospital stay (typically 10 days or more) combined with missing or incomplete baseline health metrics such as blood pressure, weight, height, or BMI.",0.927312
3,137,"(128, 64)",0.038005,"<think>\n\n</think>\n\n- ""Mentions patients aged 80 years or older with normal or near-normal systolic blood pressure and a documented BMI, regardless of whether it is classified as normal, overweight, or obese.",0.863636
4,238,"(128, 64)",0.036880,"<think>\n\n</think>\n\n- ""Mentions missing or incomplete systolic and diastolic blood pressure, height, weight, and BMI data in young adult patients (age 18–27) with limited or no prior healthcare records",0.888889
5,263,"(256, 64)",0.027364,"<think>\n\n</think>\n\n- ""Mentions a blood pressure reading with both systolic and diastolic values within the normal or borderline normal range (e.g., 104/74 mmHg, 110/70",0.654545
6,334,"(256, 64)",0.022002,"<think>\n\n</think>\n\n- ""mentions being a young adult (age 18-24) with no or limited prior medical records",0.958333
7,358,"(256, 64)",0.020355,"<think>\n\n</think>\n\n- ""The text indicates that this is the patient's first documented healthcare encounter, as evidenced by the explicit mention of 'first documented healthcare encounter', 'no prior medical records', 'first recorded healthcare admission', or 'initial documented interaction",0.896000
8,114,"(128, 32)",0.012250,"<think>\n\n</think>\n\n- ""Mentions missing or unrecorded systolic and diastolic blood pressure values in young adult patients (age 18-22) with limited prior healthcare engagement or no prior medical records",0.868636
9,503,"(256, 64)",0.010094,"<think>\n\n</think>\n\n- ""Mentions a patient aged 18 to 22 years with a BMI in the overweight range (≥25) or missing BMI data, and includes an emergency room admission or urgent care encounter with a short to",0.837209

**Save all in one json**

In [31]:
import os
import json
if not os.path.isdir(result_dir):
    os.makedirs(result_dir)
train_all_info_file = os.path.join(result_dir, "train_all_info.jsonl")
test_all_info_file = os.path.join(result_dir, "test_all_info.jsonl")
with open(test_all_info_file, 'w') as f:
    for text, label, idx in zip(test_texts, test_y, range(len(test_texts))):
        f.write(json.dumps({"idx": idx, "profile": text, "label": label}) + "\n")
with open(train_all_info_file, 'w') as f:
    for text, label, idx in zip(texts, labels, range(len(texts))):
        f.write(json.dumps({"idx": idx, "profile": text, "label": label}) + "\n")

In [32]:
from hypothesaes.sae import SparseAutoencoder, load_model, get_multiple_sae_activations, get_sae_checkpoint_name
activations, neuron_source_sae_info = get_multiple_sae_activations(sae_list, test_embeddings, return_neuron_source_info=True)

Computing activations (batchsize=16384):   0%|          | 0/1 [00:00<?, ?it/s]

Computing activations (batchsize=16384): 100%|██████████| 1/1 [00:00<00:00, 165.96it/s]
Computing activations (batchsize=16384): 100%|██████████| 1/1 [00:00<00:00, 546.06it/s]
Computing activations (batchsize=16384): 100%|██████████| 1/1 [00:00<00:00, 602.20it/s]

In [33]:
def clean_interpretation(text):
    return text.replace("<think>", "").replace("</think>", "").strip().lstrip("-").strip().strip('"')

# 创建解释字典
if multi_class:
    neuron_interpretations = {
        row['neuron_idx']: clean_interpretation(row['interpretation'])
        for _, row in results.iterrows()
    }
else:
    neuron_interpretations = {}
    for key, value in results.items():
        neuron_interpretations[key] = {
            row['neuron_idx']: clean_interpretation(row['interpretation'])
            for _, row in value.iterrows()
        }

In [34]:
import torch
def describe_from_activations(activations: np.array, neuron_interpretations: dict, threshold=0.5, extra_info =None):
    """根据 activation 向量和解释字典，返回解释列表"""

    
    descriptions = []
    for idx, value in enumerate(activations):
        if value.item() > threshold and idx in neuron_interpretations:
            if extra_info is not None:
                descriptions.append((idx, neuron_interpretations[idx], value.item(), extra_info))
            else:
                descriptions.append((idx, neuron_interpretations[idx], value.item()))
    
    # 可以按激活值排序
    descriptions = sorted(descriptions, key=lambda x: -x[2])
    return descriptions
def render_descriptions(descriptions, multiclass=False):
    if not descriptions:
        return "No meaningful activations found."

    output = ["This text likely involves:"]
    if multiclass:   
        for idx, interp, score in descriptions:
            output.append(f"- {interp} (activation={score:.2f})")
    else:
        for idx, interp, score, type in descriptions:
            output.append(f"- {interp} (activation={score:.2f}, type={type})")
    return "\n".join(output)

In [35]:
interpret_list = []
if multi_class:
    for act in activations:
        descriptions = describe_from_activations(act, neuron_interpretations, threshold=0)
        interpret_list.append(render_descriptions(descriptions, True))
else:
    for act in activations:
        descriptions = []
        for key, value in neuron_interpretations.items():
            descriptions.extend(describe_from_activations(act, value, threshold=0, extra_info=f'[{key}]'))
        interpret_list.append(render_descriptions(descriptions, False))
with open(os.path.join(result_dir, 'test_interpretations.jsonl'), "w") as f:
    for text, interpret in zip(range(len(interpret_list)), interpret_list):
        f.write(json.dumps({"text": text, "interpretation": interpret}) + "\n")

**Evaluate held-out generalization**

Finally, we evaluate whether these are good hypotheses by testing whether their natural language interpretations can predict the target variable.  

We compute annotations for each hypothesized concept on a holdout set (not seen during SAE training & feature selection).

After annotation, we output a dataframe with the following columns:
- `hypothesis`: The natural language hypothesis (which came from interpreting a predictive neuron in the SAE)
- `separation_score`: How much the target variable differs when the concept is present vs. absent (i.e., $E[Y\mid\text{concept} = 1] - E[Y\mid\text{concept} = 0]$).
- `separation_pvalue`: The t-test p-value of the null hypothesis that the separation score is 0 (i.e., the concept is not associated with the target variable).
- `regression_coef`: The coefficient of the concept in a multivariate linear regression of the target variable on all concepts.
- `regression_pval`: The p-value of the null hypothesis that the regression coefficient is 0.
- `feature_prevalence`: The fraction of examples that contain the concept.

Additionally, we output the evaluation metrics used in the paper:
- Significant hypotheses: the number of hypotheses that are significant in the multivariate regression at a specified significance level (default $0.1$) after Bonferroni correction. You can pass in a different significance level using the `corrected_pval_threshold` parameter.
- AUC or $R^2$: how well the hypotheses collectively predict the target variable in the multivariate regression.

In [36]:
# holdout_df = pd.read_json(os.path.join(base_dir, "yelp-demo-holdout-2K.json"), lines=True)
# holdout_texts = holdout_df['text'].tolist()
# holdout_labels = holdout_df['stars'].values
from hypothesaes.quickstart import evaluate_hypotheses
if multi_class:
    metrics, evaluation_df = evaluate_hypotheses(
        hypotheses_df=results,
        texts=test_texts,
        labels=label_test,
        cache_name=CACHE_NAME,
        max_words_per_example=1024,
        annotator_model="Qwen/Qwen3-32B",  # Use the same model as for training
        classification=True
    )

    pd.set_option('display.max_colwidth', None)
    display(evaluation_df)
    pd.reset_option('display.max_colwidth')

    print("\nHoldout Set Metrics:")
    print(f"R² Score: {metrics['r2']:.3f}")
    print(f"Significant hypotheses: {metrics['Significant'][0]}/{metrics['Significant'][1]} " 
        f"(p < {metrics['Significant'][2]:.3e})")
else:
    metrics, evaluation_df = {}, {}
    for key in number_dict.keys():
        key_norm = key.replace("/", "or")
        key_norm = key_norm.replace(" ", "_")
        converted_key = {number_dict[dic_key]: 1 if dic_key == key else 0 for dic_key in number_dict.keys()}
        converted_label = [converted_key[label] for label in label_test]
        metrics[key], evaluation_df[key] = evaluate_hypotheses(
            hypotheses_df=results[f'{key}_vs_rest'],
            texts=test_texts,
            labels=converted_label,
            cache_name=os.path.join(CACHE_NAME, CACHE_SIGNAL, f"{key}_vs_rest"),
            max_words_per_example=1024,
            annotator_model="Qwen/Qwen3-32B",  # Use the same model as for training
            classification=True
        )
        evaluation_df[key].to_csv(os.path.join(result_dir, f"evaluation_{key_norm}.csv"), index=False)
        with open(os.path.join(result_dir, f"metrics_{key_norm}.json"), "w") as f:
            json.dump(metrics[key], f, indent=4)
        pd.set_option('display.max_colwidth', None)
        display(evaluation_df[key])
        pd.reset_option('display.max_colwidth')
        print(f"\nHoldout Set Metrics for {key}:")
        print(f"R² Score: {metrics[key]['r2']:.3f}")
        print(f"Significant hypotheses: {metrics[key]['Significant'][0]}/{metrics[key]['Significant'][1]} " 
            f"(p < {metrics[key]['Significant'][2]:.3e})")

Step 1: Annotating texts with 10 hypotheses
Found 357 cached items; annotating 10323 uncached items

Annotating: 100%|██████████| 10323/10323 [07:06<00:00, 24.19it/s]

Step 2: Computing predictiveness of hypothesis annotations
Optimization terminated successfully.
         Current function value: 0.594489
         Iterations 6

,hypothesis,separation_score,separation_pval,regression_coef,regression_pval,feature_prevalence
8,"<think>\n\n</think>\n\n- ""Mentions missing or unrecorded systolic and diastolic blood pressure values in young adult patients (age 18-22) with limited prior healthcare engagement or no prior medical records",0.371109,3.726004e-06,0.346129,6.128121e-01,0.037453
9,"<think>\n\n</think>\n\n- ""Mentions a patient aged 18 to 22 years with a BMI in the overweight range (≥25) or missing BMI data, and includes an emergency room admission or urgent care encounter with a short to",0.339317,6.236276e-08,0.940064,2.305713e-02,0.062734
4,"<think>\n\n</think>\n\n- ""Mentions missing or incomplete systolic and diastolic blood pressure, height, weight, and BMI data in young adult patients (age 18–27) with limited or no prior healthcare records",0.313569,6.930725e-09,0.884138,1.226209e-02,0.086142
6,"<think>\n\n</think>\n\n- ""mentions being a young adult (age 18-24) with no or limited prior medical records",0.312842,6.828891e-06,-0.052511,9.136913e-01,0.050562
7,"<think>\n\n</think>\n\n- ""The text indicates that this is the patient's first documented healthcare encounter, as evidenced by the explicit mention of 'first documented healthcare encounter', 'no prior medical records', 'first recorded healthcare admission', or 'initial documented interaction",0.135130,1.460455e-05,0.599591,2.693295e-05,0.395131
5,"<think>\n\n</think>\n\n- ""Mentions a blood pressure reading with both systolic and diastolic values within the normal or borderline normal range (e.g., 104/74 mmHg, 110/70",0.083271,9.763205e-03,0.158058,3.141309e-01,0.341760
1,"<think>\n\n</think>\n\n- ""Lacks documentation of height, weight, systolic and diastolic blood pressure, and BMI",-0.105902,7.141685e-04,-0.514434,1.467157e-03,0.390449
3,"<think>\n\n</think>\n\n- ""Mentions patients aged 80 years or older with normal or near-normal systolic blood pressure and a documented BMI, regardless of whether it is classified as normal, overweight, or obese.",-0.217410,1.482262e-04,-0.405085,1.569106e-01,0.076779
0,"<think>\n\n</think>\n\n- ""The text mentions the patient being admitted through the emergency room or having an emergency/urgent admission, and also emphasizes the patient's advanced age (typically 80 years or older) combined with missing or undocumented vital signs such",-0.304906,1.312111e-17,-1.027649,2.004521e-08,0.231273
2,"<think>\n\n</think>\n\n- ""Mentions an extended length of hospital stay (typically 10 days or more) combined with missing or incomplete baseline health metrics such as blood pressure, weight, height, or BMI.",-0.381764,4.385280e-18,-1.752103,5.292900e-14,0.134831

Holdout Set Metrics:
R² Score: 0.142
Significant hypotheses: 4/10 (p < 1.000e-02)

In [37]:
if multi_class:
        pd.set_option('display.max_colwidth', None)
        display(evaluation_df)
        pd.reset_option('display.max_colwidth')
        print("\nHoldout Set Metrics:")
        print(f"R² Score: {metrics['r2']:.3f}")
        print(f"Significant hypotheses: {metrics['Significant'][0]}/{metrics['Significant'][1]} " 
            f"(p < {metrics['Significant'][2]:.3e})")
        evaluation_df.to_csv(os.path.join(result_dir, "evaluation.csv"), index=False)
        with open(os.path.join(result_dir, "metrics.json"), "w") as f:
            json.dump(metrics, f, indent=4)
        
else:
        for key in metrics.keys():
                # print(metrics[key])
                pd.set_option('display.max_colwidth', None)
                display(evaluation_df[key])
                pd.reset_option('display.max_colwidth')
                print(f"\nHoldout Set Metrics for {key}:")
                print(f"R² Score: {metrics[key]['r2']:.3f}")
                print(f"Significant hypotheses: {metrics[key]['Significant'][0]}/{metrics[key]['Significant'][1]} " 
                f"(p < {metrics[key]['Significant'][2]:.3e})")
                evaluation_df[key].to_csv(os.path.join(result_dir, f"evaluation_{key}.csv"), index=False)
                with open(os.path.join(result_dir, f"metrics_{key}.json"), "w") as f:
                    json.dump(metrics[key], f, indent=4)

,hypothesis,separation_score,separation_pval,regression_coef,regression_pval,feature_prevalence
8,"<think>\n\n</think>\n\n- ""Mentions missing or unrecorded systolic and diastolic blood pressure values in young adult patients (age 18-22) with limited prior healthcare engagement or no prior medical records",0.371109,3.726004e-06,0.346129,6.128121e-01,0.037453
9,"<think>\n\n</think>\n\n- ""Mentions a patient aged 18 to 22 years with a BMI in the overweight range (≥25) or missing BMI data, and includes an emergency room admission or urgent care encounter with a short to",0.339317,6.236276e-08,0.940064,2.305713e-02,0.062734
4,"<think>\n\n</think>\n\n- ""Mentions missing or incomplete systolic and diastolic blood pressure, height, weight, and BMI data in young adult patients (age 18–27) with limited or no prior healthcare records",0.313569,6.930725e-09,0.884138,1.226209e-02,0.086142
6,"<think>\n\n</think>\n\n- ""mentions being a young adult (age 18-24) with no or limited prior medical records",0.312842,6.828891e-06,-0.052511,9.136913e-01,0.050562
7,"<think>\n\n</think>\n\n- ""The text indicates that this is the patient's first documented healthcare encounter, as evidenced by the explicit mention of 'first documented healthcare encounter', 'no prior medical records', 'first recorded healthcare admission', or 'initial documented interaction",0.135130,1.460455e-05,0.599591,2.693295e-05,0.395131
5,"<think>\n\n</think>\n\n- ""Mentions a blood pressure reading with both systolic and diastolic values within the normal or borderline normal range (e.g., 104/74 mmHg, 110/70",0.083271,9.763205e-03,0.158058,3.141309e-01,0.341760
1,"<think>\n\n</think>\n\n- ""Lacks documentation of height, weight, systolic and diastolic blood pressure, and BMI",-0.105902,7.141685e-04,-0.514434,1.467157e-03,0.390449
3,"<think>\n\n</think>\n\n- ""Mentions patients aged 80 years or older with normal or near-normal systolic blood pressure and a documented BMI, regardless of whether it is classified as normal, overweight, or obese.",-0.217410,1.482262e-04,-0.405085,1.569106e-01,0.076779
0,"<think>\n\n</think>\n\n- ""The text mentions the patient being admitted through the emergency room or having an emergency/urgent admission, and also emphasizes the patient's advanced age (typically 80 years or older) combined with missing or undocumented vital signs such",-0.304906,1.312111e-17,-1.027649,2.004521e-08,0.231273
2,"<think>\n\n</think>\n\n- ""Mentions an extended length of hospital stay (typically 10 days or more) combined with missing or incomplete baseline health metrics such as blood pressure, weight, height, or BMI.",-0.381764,4.385280e-18,-1.752103,5.292900e-14,0.134831

Holdout Set Metrics:
R² Score: 0.142
Significant hypotheses: 4/10 (p < 1.000e-02)

In [38]:
pd.set_option('display.max_colwidth', None)
display(evaluation_df)
pd.reset_option('display.max_colwidth')
print("\nHoldout Set Metrics:")
# print(f"R² Score: {metrics['r2']:.3f}")
print(f"Significant hypotheses: {metrics['Significant'][0]}/{metrics['Significant'][1]} " 
    f"(p < {metrics['Significant'][2]:.3e})")
evaluation_df.to_csv(os.path.join(result_dir, "evaluation.csv"), index=False)
with open(os.path.join(result_dir, "metrics.json"), "w") as f:
    json.dump(metrics, f, indent=4)

,hypothesis,separation_score,separation_pval,regression_coef,regression_pval,feature_prevalence
8,"<think>\n\n</think>\n\n- ""Mentions missing or unrecorded systolic and diastolic blood pressure values in young adult patients (age 18-22) with limited prior healthcare engagement or no prior medical records",0.371109,3.726004e-06,0.346129,6.128121e-01,0.037453
9,"<think>\n\n</think>\n\n- ""Mentions a patient aged 18 to 22 years with a BMI in the overweight range (≥25) or missing BMI data, and includes an emergency room admission or urgent care encounter with a short to",0.339317,6.236276e-08,0.940064,2.305713e-02,0.062734
4,"<think>\n\n</think>\n\n- ""Mentions missing or incomplete systolic and diastolic blood pressure, height, weight, and BMI data in young adult patients (age 18–27) with limited or no prior healthcare records",0.313569,6.930725e-09,0.884138,1.226209e-02,0.086142
6,"<think>\n\n</think>\n\n- ""mentions being a young adult (age 18-24) with no or limited prior medical records",0.312842,6.828891e-06,-0.052511,9.136913e-01,0.050562
7,"<think>\n\n</think>\n\n- ""The text indicates that this is the patient's first documented healthcare encounter, as evidenced by the explicit mention of 'first documented healthcare encounter', 'no prior medical records', 'first recorded healthcare admission', or 'initial documented interaction",0.135130,1.460455e-05,0.599591,2.693295e-05,0.395131
5,"<think>\n\n</think>\n\n- ""Mentions a blood pressure reading with both systolic and diastolic values within the normal or borderline normal range (e.g., 104/74 mmHg, 110/70",0.083271,9.763205e-03,0.158058,3.141309e-01,0.341760
1,"<think>\n\n</think>\n\n- ""Lacks documentation of height, weight, systolic and diastolic blood pressure, and BMI",-0.105902,7.141685e-04,-0.514434,1.467157e-03,0.390449
3,"<think>\n\n</think>\n\n- ""Mentions patients aged 80 years or older with normal or near-normal systolic blood pressure and a documented BMI, regardless of whether it is classified as normal, overweight, or obese.",-0.217410,1.482262e-04,-0.405085,1.569106e-01,0.076779
0,"<think>\n\n</think>\n\n- ""The text mentions the patient being admitted through the emergency room or having an emergency/urgent admission, and also emphasizes the patient's advanced age (typically 80 years or older) combined with missing or undocumented vital signs such",-0.304906,1.312111e-17,-1.027649,2.004521e-08,0.231273
2,"<think>\n\n</think>\n\n- ""Mentions an extended length of hospital stay (typically 10 days or more) combined with missing or incomplete baseline health metrics such as blood pressure, weight, height, or BMI.",-0.381764,4.385280e-18,-1.752103,5.292900e-14,0.134831

Holdout Set Metrics:
Significant hypotheses: 4/10 (p < 1.000e-02)

In [39]:
evaluation_df
with open(os.path.join(result_dir, 'hypotheses_info.jsonl'), "w") as f:
    for _, row in evaluation_df.iterrows():
        f.write(json.dumps(row.to_dict()) + "\n")

In [40]:
#output hypothesis and its coef in csv
df_coef = evaluation_df[['hypothesis', 'regression_coef']]
df_coef.to_csv(os.path.join(result_dir, 'hypothesis_coef.csv'), index=False)